/*	Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/

#ident	"@(#)_xdrMsgs.h	1.3	90/03/14 SMI"	/* SVr4.0 1.3	*/
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>


struct physicalMsgTag {
	long physicalMsgSize;
};
typedef struct physicalMsgTag physical_MsgTag;
bool_t xdr_physicalMsgTag();
