#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile.targ	1.1	99/01/25 SMI"
#
# lib/libplot/t450/spec/Makefile.targ

LIBRARY	=	lib450.a
VERS	=	.1

OBJECTS	=	t450.o

SPECCPP =
