#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.4	97/11/13 SMI"
#

.KEEP_STATE:

include ../Makefile.com
include ../../Makefile.cmd.64

#catalog: $(MSGDOMAIN64) $(POFILE)
#	$(RM) $(MSGDOMAIN64)/$(POFILE)
#	$(CP) $(POFILE) $(MSGDOMAIN64)

catalog:

install: all
