#
# ident	"@(#)Makefile	1.4	92/12/15 SMI"
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#
# cmd/lp/filter/postscript/macros/Makefile
#

FILES =		color pictures tmac.color tmac.pictures

TXTS =		README

.KEEP_STATE:

all:		$(TXTS) $(FILES)

install clean clobber strip lint:

