#
# Copyright (c) 1999, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.2	99/03/26 SMI"
#
# lib/cfgadm_plugins/pci/i386/Makefile

MAPDIR= ../spec/i386
include ../Makefile.com

.KEEP_STATE:

install: all $(ROOTLIBS) $(ROOTLINKS)
