#
# Copyright (c) 1997-1998, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.2	98/04/20 SMI"
#
# lib/ac/sparcv9/Makefile

include ../Makefile.com
include ../../../Makefile.lib.64

.KEEP_STATE:

install: all $(ROOTLIBS64) $(ROOTLINKS64)
