#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile.targ	1.1	99/01/25 SMI"
#
# ucblib/libdbm/spec/Makefile.targ

LIBRARY	=	libdbm.a
VERS	=	.1

OBJECTS	=	dbm.o

TRANSCPP =
SPECCPP =	-I$(ROOT)/usr/ucbinclude
