#
#ident  "@(#)Makefile 1.1     99/07/07 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/nsswitch/ldap/sparcv9/Makefile
#

LIBRARY = libnss_ldap.so

include ../Makefile.com
include ../../../Makefile.lib.64

LIBS= $(DYNLIB1) $(DYNLIB2)

.KEEP_STATE:

install: all $(ROOTLIBS64) $(ROOTLINKS64)
