#
# Copyright (c) 1998 by Sun Microsystems, Inc.
# All rights reserved.
#
# ident	"@(#)Makefile	1.1	98/12/14 SMI"
#
# cmd/sort/sparcv9/Makefile

include ../Makefile.com
include ../../Makefile.cmd.64

# doesn't install ROOTXPG4PROG64 yet, no such place
install : all $(ROOTPROG64)
