#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident  "@(#)Makefile	1.5    99/03/31 SMI"
#

include ../Makefile.com

DATAFILES += depend
CLOBBERFILES += $(DATAFILES)

.KEEP_STATE:

all: $(FILES)

install: all pkg

include ../Makefile.targ
