#
# Copyright (c) 1999, by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident  "@(#)Makefile.targ 1.1     99/03/09 SMI"
#
# lib/libmail/spec/Makefile.targ

LIBRARY	=	libmail.a
VERS	=	.1

OBJECTS	=	mail.o

SPECCPP =       -I../../inc
