#
#ident	"@(#)Makefile.targ	1.1	98/09/29 SMI"
#
# Copyright (c) 1998 by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/sgs/dis/Makefile.targ
#

%.o:		../common/%.c
		$(COMPILE.c) $<

.KEEP_STATE:

all:		$(PROG)

install:	all $(ROOTCCSBINPROG)

clean:
		$(RM) $(OBJS) $(CLEANFILES)

lint:		$(LINTOUT32)

$(PROG):	$$(OBJS)
		$(LINK.c) $(OBJS) -o $@ $(LDLIBS)
		$(POST_PROCESS)

		
include		$(SRC)/cmd/Makefile.targ
include		$(SRC)/cmd/sgs/Makefile.targ
