#
#ident	"@(#)Makefile	1.3	95/01/27 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
#
# cmd/eeprom/sparc/sun4m/Makefile
#
# Platform specific Makefile for the eeprom command.
#
# PLATFORM is the target for the binary instalation.
#
# PLATLINKS is a list of platforms which are to be linked to this binary
#	at the file level.
#
SRCDIR		= ../..
PLATFORM	= sun4m
PLATLINKS	=

include $(SRCDIR)/Makefile.com

.KEEP_STATE:

all:	$(PROG)

include $(SRCDIR)/Makefile.targ
