#ident "@(#)Makefile	1.1	97/11/09 SMI"
#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#
# cmd/syslogd/i386/Makefile

include ../Makefile.com

all: $(PROG) $(VARSYSLOG) $(VARAUTHLOG)

install: all $(ROOTUSRSBINPROG) $(ROOTETCCONFIG) $(ROOTLIBROTATE) logfiles
