#
#ident  "@(#)Makefile 1.4     98/07/11 SMI"        /*      */
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
#
# cmd/fs.d/nfs/nfsfind/Makefile

FSTYPE=		nfs
LIBPROG=	nfsfind
SRCS=		nfsfind.sh

include		../../Makefile.fstype

OWNER=		root
GROUP=		sys
