/*
 * Copyright (c) 1997, by Sun Microsystems, Inc.
 * All rights reserved.
 */

/*
 * This file was derived from the MIT 1.0 source release.
 */

#ifndef	_GSSAPI_ERR_GENERIC_H
#define	_GSSAPI_ERR_GENERIC_H

#pragma ident	"@(#)gssapi_err_generic.h 1.6	99/07/18 SMI"

#ifdef	__cplusplus
extern "C" {
#endif

/*
 * gssapi_err_generic.h:
 * This file is automatically generated; please do not edit it.
 */
#define	G_BAD_SERVICE_NAME			(-2045022976L)
#define	G_BAD_STRING_UID			(-2045022975L)
#define	G_NOUSER				(-2045022974L)
#define	G_VALIDATE_FAILED			(-2045022973L)
#define	G_BUFFER_ALLOC				(-2045022972L)
#define	G_BAD_MSG_CTX				(-2045022971L)
#define	G_WRONG_SIZE				(-2045022970L)
#define	G_BAD_USAGE				(-2045022969L)
#define	G_UNKNOWN_QOP				(-2045022968L)
#define	G_NO_HOSTNAME				(-2045022967L)
#define	G_BAD_HOSTNAME				(-2045022966L)
#define	G_WRONG_MECH				(-2045022965L)
#define	G_BAD_TOK_HEADER			(-2045022964L)
#define	G_BAD_DIRECTION				(-2045022963L)
#define	ERROR_TABLE_BASE_ggss (-2045022976L)

/* for compatibility with older versions... */
#define	ggss_err_base ERROR_TABLE_BASE_ggss

#ifdef	__cplusplus
}
#endif

#endif	/* _GSSAPI_ERR_GENERIC_H */
