#
# Copyright (c) 1998 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident "@(#)Makefile.targ	1.1 99/07/11 SMI"
#
# lib/ami/spec/Makefile.targ

LIBRARY	=	libami.a
VERS	=	.1

OBJECTS	=	ami.o
