#
#ident	"@(#)Makefile	1.1	94/06/28 SMI"
#
# Copyright (c) 1994 by Sun Microsystems, Inc.
#

include ../Makefile.com

.KEEP_STATE:

all:		$(DYNLIB)
install:	all $(ROOTDYNLIB)

include ../Makefile.targ
