"%%EndComments\n",
"%\n",
"% PostScript Prologue for lwlp LaserWriter Line Printer\n",
"% @(#)prologue.h 1.1     99/05/17 SMI\n",
"%\n",
"/SFT {findfont exch scalefont setfont}bind def\n",
"/SWT {( ) stringwidth pop dup /W exch def neg /NW exch def}bind def\n",
"/SPG {/SV save def translate dup scale rotate}bind def\n",
"/EPG {SV restore}bind def\n",
"/FPG {/#copies exch def showpage}bind def\n",
"/B {NW 0 rmoveto}def\n",
"/M /moveto load def\n",
"/T {W mul 0 rmoveto}def\n",
"/S /show load def\n",
"/Z {0 exch moveto}bind def\n",
"/SHD {save 5 1 roll			% S x1 y1 x0 y0\n",
"	2 copy moveto			% S x1 y1 x0 y0\n",
"	3 index exch lineto		% S x1 y1 x0\n",
"	3 -1 roll 2 index lineto	% S y1 x0\n",
"	exch lineto			% S\n",
"	0.95 setgray fill		% S\n",
"	restore}def\n",
"%%EndProlog\n",
