#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile.common	1.3	99/09/23 SMI"

#
# List of common MDB modules that every ISA's build subdirectory will
# need to build.  This will be referenced by the lower-level Makefiles.
#
COMMON_MODULES = \
	mdb_ds \
	mdb_ks \
	mdb_test \
	genunix \
	ip \
	ipc \
	krtld \
	lofs \
	logindmux \
	nfs \
	ptm
