#
#ident	"@(#)Makefile	1.1	96/07/03 SMI"
#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.
#
# pkgdefs/SUNWdhcsu/Makefile
#

include ../Makefile.com

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
