#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#
#pragma ident "@(#)Makefile	1.2 97/10/27 SMI"
#
#
# lib/fn/context/onc_ns/libfnsp/i386/Makefile
#

FNRPATH=	/usr/lib/fn
FNSPLIB= 	-L$(FNLIBDIR) -lfnsp

include ../Makefile.com

.KEEP_STATE:

debug install tcov: $(ROOTLIBDIR) $(ROOTLIBS) $(ROOTFNLINKS)
