#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	97/06/13 SMI"

include		$(SRC)/cmd/sgs/0@0/Makefile.com

.KEEP_STATE:

install:	all $(ROOTLIBDIR64)/$(DYNLIB)

include		$(SRC)/cmd/sgs/0@0/Makefile.targ
include		../../Makefile.sub.64

