#
#ident	"@(#)Makefile	1.2	96/05/06 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
#

include ../Makefile.com

DATAFILES += depend i.preserve

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
