#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.3	99/01/25 SMI"
#
# lib/libtnfprobe/sparc/Makefile

MAPDIR=	../spec/sparc
include ../Makefile.com

.KEEP_STATE:

install: all $(ROOTLIBS) $(ROOTLINKS)
