/*
 * Copyright (c) 1986-1992 by Sun Microsystems Inc.
 */

#include <rpc/rpc.h>
#include <sys/types.h>
#include <rpc/trace.h>
#include <rpcsvc/ypupd.h>
/* @(#)ypupdate_prot.x 1.4 88/02/08 Copyr 1986, Sun Micro */

/*
 * Compiled from ypupdate_prot.x using rpcgen
 * This is NOT source code!
 * DO NOT EDIT THIS FILE!
 */

bool_t
xdr_yp_buf(xdrs, objp)
	XDR *xdrs;
	yp_buf *objp;
{
	trace1(TR_xdr_yp_buf, 0);
	if (!xdr_bytes(xdrs, (char **)&objp->yp_buf_val,
		(u_int *)&objp->yp_buf_len, MAXYPDATALEN)) {
		trace1(TR_xdr_yp_buf, 1);
		return (FALSE);
	}
	trace1(TR_xdr_yp_buf, 1);
	return (TRUE);
}

bool_t
xdr_ypupdate_args(xdrs, objp)
	XDR *xdrs;
	ypupdate_args *objp;
{
	trace1(TR_xdr_ypupdate_args, 0);
	if (!xdr_string(xdrs, &objp->mapname, MAXMAPNAMELEN)) {
		trace1(TR_xdr_ypupdate_args, 1);
		return (FALSE);
	}
	if (!xdr_yp_buf(xdrs, &objp->key)) {
		trace1(TR_xdr_ypupdate_args, 1);
		return (FALSE);
	}
	if (!xdr_yp_buf(xdrs, &objp->datum)) {
		trace1(TR_xdr_ypupdate_args, 1);
		return (FALSE);
	}
	trace1(TR_xdr_ypupdate_args, 1);
	return (TRUE);
}

bool_t
xdr_ypdelete_args(xdrs, objp)
	XDR *xdrs;
	ypdelete_args *objp;
{
	trace1(TR_xdr_ypdelete_args, 0);
	if (!xdr_string(xdrs, &objp->mapname, MAXMAPNAMELEN)) {
		trace1(TR_xdr_ypdelete_args, 1);
		return (FALSE);
	}
	if (!xdr_yp_buf(xdrs, &objp->key)) {
		trace1(TR_xdr_ypdelete_args, 1);
		return (FALSE);
	}
	trace1(TR_xdr_ypdelete_args, 1);
	return (TRUE);
}
