/*
 *	Copyright (c) 1993 Sun Microsystems, Inc.
 */

#ifndef _SYS_UNIX_BB_INFO_H
#define	_SYS_UNIX_BB_INFO_H

#pragma ident	"@(#)unix_bb_info.h	1.1	93/05/07 SMI"

#ifdef	__cplusplus
extern "C" {
#endif

/*
 *  data structures for kernel basic block coverage via kcov
 */

#define	NMI_LEVEL	15

/*
 *	struct bb_info is built in to the compiler
 *	Don't change this structure except to reflect
 *	changes to the code generated by the compiler
 */
struct bb_info {
	int			bb_initflag;
	char			*bb_filename;
	unsigned int		*bb_counters;
	int			bb_ncounters;
	struct bb_info 		*bb_next;
};

#ifdef	__cplusplus
}
#endif

#endif	/* _SYS_UNIX_BB_INFO_H */
