#
#ident	"@(#)Makefile	1.1	99/01/25 SMI"
#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/abi/daa2x/spec2truss/sparc/Makefile

.KEEP_STATE:

include		../Makefile.targ
