#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	99/08/15 SMI"
#
# lib/libcpc/sparcv9/Makefile

MAPDIR=	../spec/sparcv9

OBJECTS = conf_ultra.o event_ultra.o
include ../Makefile.com
include ../../Makefile.lib.64

.KEEP_STATE:

install: all $(ROOTLIBS64) $(ROOTLINKS64) $(ROOTLINT64)
