#! /bin/sh
#
# ident "@(#)preinstall 1.2	99/06/08 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#

PATH="/bin:/usr/bin:/usr/sbin:${PATH}"
export PATH

TMP=/tmp/$$.pcmemvold

remove_token()
{

    cp $1 $TMP

    (   echo "g/$2/s///g"
        echo 'g/ $/s///g'
        echo 'w'
        echo 'q'
    ) | ed -s $TMP >/dev/null

    cp $TMP $1
    rm -f $TMP
}

#
# vold.conf processing
#

FILE="$BASEDIR/etc/vold.conf"

if test -f $FILE ; then

  #
  # clear out any old pcmem lines in vold.conf
  #
  egrep -v 'use pcmem drive' $FILE >$TMP
  cp $TMP $FILE
  rm -f $TMP

  #
  # clear out any old pcmem entries in vold.conf
  #
  remove_token "$FILE" 'pcmem'
fi

#
# rmmount.conf processing
#
FILE="$BASEDIR/etc/rmmount.conf"

if test -f $FILE ; then

    #
    # clear out any old pcmem entries in rmmount.conf
    #
    remove_token "$FILE" 'pcmem'
fi

exit 0

