#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.1	99/08/10 SMI"
#
# lib/librcm/ia64/Makefile
#

MAPDIR=	../spec/ia64
include ../Makefile.com
include ../../Makefile.lib.64

LIBS=	$(DYNLIB)

.KEEP_STATE:

all: $(LIBS)

install: all $(ROOTLIBS64) $(ROOTLINKS64)
