#
#pragma ident	"@(#)Makefile	1.4	99/04/26 SMI"
#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libxcurses/i386/Makefile

MAPDIR=	../spec/i386
include ../Makefile.com

DYNFLAGS += $(DYNFLAGS32)

.KEEP_STATE:

all: $(LIBS) 

install: all $(ROOTLIBS)
