#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.3	99/01/25 SMI"
#
# lib/nametoaddr/straddr/sparcv9/Makefile

MAPDIR=	../spec/sparcv9
include ../Makefile.com
include ../../../Makefile.lib.64

LIBS=	$(DYNLIB)

.KEEP_STATE:

install: all $(ROOTLIBS64) $(ROOTLINKS64)
