#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.1	99/08/10 SMI"
#
# lib/librcm/i386/Makefile

MAPDIR=	../spec/i386
include ../Makefile.com

all: $(LIBS) $(STATICLIB)

.KEEP_STATE:

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
