#
#ident	"@(#)Makefile	1.4	97/07/21 SMI"
#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/sysdef/sparcv9/Makefile

include ../Makefile.com
include ../../Makefile.cmd.64

CFLAGS64 += -D_ELF64

install: all $(ROOTUSRSBINPROG64)
