#
#ident	"@(#)Makefile	1.10	98/09/30 SMI"
#
# Copyright (c) 1998 by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/sgs/dis/sparc/Makefile
#

include		../Makefile.com

.KEEP_STATE:

MACHOBJS=	bits.o disasm.o sas_tables.o tables.o

DEFLIST=	-DM32 -DFBO -DSPARC -DELF

include		../Makefile.targ
