#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.2	99/09/20 SMI"
#

include ../Makefile.com

DATAFILES += i.preserve depend

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
