#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident "@(#)Makefile.export	1.1 99/07/23 SMI"
#
#	Makefile for AMI commands
#

include $(SRC)/Makefile.master

.KEEP_STATE:

# make rules
all install clean clobber debug check lint install_h catalog _msg: FRC

FRC:
