# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident "@(#)Makefile	1.7	99/07/22  SMI"
#
# SUNWluxop/Makefile
 
include ../Makefile.com

DATAFILES += depend

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
