#
# Copyright (c) 1997 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	97/09/07 SMI"
#

include ../Makefile.com
include ../../Makefile.cmd.64

CPPFLAGS += -D__sparcv9 -I$(ROOT)/usr/include/v9
CFLAGS64 += -D_ELF64

install: all $(ROOTUSRSBINPROG64)
