#
#ident  "@(#)Makefile	1.2	00/09/14 SMI"
#
# Copyright (c) 1998, by Sun Microsystems, Inc.
# All rights reserved.
#

MAPDIR= ../spec/sparcv9

include ../Makefile.com
include ../../Makefile.lib.64

.KEEP_STATE:

all: $(LIBS)

install: all $(ROOTLIBS64) $(ROOTLINKS64)
