#
# Copyright (c) 1998 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident "@(#)Makefile	1.1 99/07/11 SMI"
#
#	Makefile for sparc
#

include ../Makefile.com

OBJDIR=objs
PICDIR=pics

.KEEP_STATE:

all: $(OBJDIR) $(PICDIR) $(LIBS)

install: all $(ROOTLIBS) $(ROOTLINKS)
