#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.2	97/06/13 SMI"

include		$(SRC)/cmd/sgs/0@0/Makefile.com

.KEEP_STATE:

include		$(SRC)/cmd/sgs/0@0/Makefile.targ

install:	all $(ROOTDYNLIB)

