#!/sbin/sh
#
# Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T.
# All rights reserved.
#
# THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
# The copyright notice above does not evidence any
# actual or intended publication of such source code.
#
# Copyright (c) 1991-1997 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)drvconfig	1.5	97/12/08 SMI"

if [ -n "$_INIT_RECONFIG" ]; then
	echo 'Configuring the /devices directory'
	/usr/sbin/drvconfig
fi
