#!/sbin/sh
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)initpcihpc	1.1	99/04/13 SMI"

case "$1" in
'start')
	pcihpcdevs=`echo /dev/pcihpc/*`
	[ "$pcihpcdevs" = '/dev/pcihpc/*' ] && exit 0

	for dev in $pcihpcdevs; do
		sh -c "echo < $dev" >/dev/null 2>&1
	done
	;;

'stop')
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 0
