#!/sbin/sh
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)MOUNTFSYS	1.16	99/09/21 SMI"

if [ -z "$_INIT_PREV_LEVEL" ]; then
	set -- `/usr/bin/who -r`
	_INIT_PREV_LEVEL="$9"
fi

if [ $_INIT_PREV_LEVEL = S ]; then
	# Mount all local filesystems.  After this, /tmp will be appropriately
	# mounted so fire off a ps in the background to build ps_data.

	cd /; /sbin/mountall -l
	/usr/bin/ps -o pid >/dev/null 2>&1 &
fi

# Make sure /usr subtree is present by testing for /usr/sbin

if [ ! -d /usr/sbin ]; then
	echo "WARNING: /usr subtree is missing: changing to single user mode"
	/sbin/init S
fi

#
# If there are non-global UFS filesystems with quotas, check and enable them.
#

# vlist is the non-global filesystems in vfstab requesting quotas
vlist=`/usr/bin/nawk '$1 !~ /^(#|-)/ && $4 == "ufs" {
	if (match($7, "(^|,)(quota|rq)(,|$)") != 0 &&
	    match($7, "(^|,)global(,|$)") == 0) print $1; }' /etc/vfstab`

if [ -n "$vlist" ]; then
	# mlist is the filesystems in mnttab that are ufs, mounted rw,
	# and without quotas turned on
	mlist=`/usr/sbin/mount -p | /usr/bin/nawk '$4 == "ufs" {
		if (match($7, "(^|,)ro(,|$)") == 0) print $1; }'`

	# qlist is the intersection of vlist and mlist
	qlist=`echo "$vlist\n-\n$mlist" | \
		/usr/bin/nawk '{if ($1 == "-") { mlist = 1; }
			else if (mlist == 0) { vlist[$1] = 1; }
			else if (vlist[$1]) { print $1; } }'`

	#
	# Just check and enable the non-global UFS file systems with quotas
	# enabled. Note that "quotacheck -a" and "quotaon -a" will try
	# to process all UFS entries with quotas rather than excluding
	# the entries with the global option (the global entries are handled
	# later in another script if the cluster package is installed).
	#
	if [ -n "$qlist" ]; then
		echo 'Checking UFS quotas: \c'
		/usr/sbin/quotacheck -p $qlist
		echo 'done.'
		/usr/sbin/quotaon $qlist
	fi
fi
