#
# Copyright (c) 1997 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	97/09/07 SMI"
#

include ../Makefile.com

CPPFLAGS += -D__sparc -I$(ROOT)/usr/include/v7

install: all $(ROOTUSRSBINPROG32)
