#
#ident  "@(#)Makefile	1.2    95/10/03 SMI"
#
# Copyright (c) 1995 by Sun Microsystems, Inc.
#

include ../Makefile.com

DATAFILES += depend

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
