#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.5	99/01/25 SMI"
#
# lib/libcmd/sparc/Makefile
#

MAPDIR=	../spec/sparcv9

include ../Makefile.com
include ../../Makefile.lib.64

LIBS = $(DYNLIB) $(LINTLIB)

.KEEP_STATE:

all: $(TXTS) $(LIBS)

install: all $(ROOTLIBS64) $(ROOTLINKS64)
