#
# Copyright (c) 1996-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.8	99/01/25 SMI"
#
# cmd/sgs/libelf/sparcv9/Makefile

MAPDIR=		../spec/sparcv9
include		../Makefile.com

LINTFLAGS64 +=	-D__sparcv9
MISCOBJS=	$(MISCOBJS64)

.KEEP_STATE:

include		../Makefile.targ.64
