#
#ident	"@(#)Makefile.targ	1.1	99/01/11 SMI"
#
# Copyright (c) 1998 by Sun Microsystems, Inc.
# All rights reserved.
#
# common target definitions for tool builds

clobber: clean
	-$(RM) $(PROG) $(CLOBBERFILES)

lint_PROG:
	$(LINT.c) $(PROG).c

lint_SRCS:
	$(LINT.c) $(SRCS)

