#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	99/10/14 SMI"
#
# lib/liblwp_db/sparcv9/Makefile

XARCH = -Xarch=v9

MAPDIR=	../spec/sparcv9

include ../Makefile.com
include ../../Makefile.lib.64

.KEEP_STATE:

install: all $(ROOTLIBDIR64) .WAIT $(ROOTLIBS64) $(ROOTLINKS64) $(ROOTLINT64)
