#
#ident "@(#)Makefile 1.13 95/05/05"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
#

include ../Makefile.com

DATAFILES += 

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
