#
#ident	"@(#)Makefile	1.1	97/06/30 SMI"
#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# psm/stand/lib/boot/sparc/sun4u/Makefile
#
# Platform-specific, but shared between platforms.
#

PLATFORM =	sun4u
ARCHVERS =	v9
TOPDIR =	../../../../../..
PLATSRCS =

include ../Makefile.com
