#
#pragma ident	"@(#)Makefile	1.3	99/01/25 SMI"
#
# Copyright (c) 1995-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# libbsm/i386/Makefile

MAPDIR=	../spec/i386

include		../Makefile.com

.KEEP_STATE:

LIBS +=		$(DYNLIB) $(LINTLIB)

all: $(LIBS)

install:	all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
