#
#ident	"@(#)Makefile	1.2	97/08/27 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/nsswitch/nisplus/sparcv9/Makefile
#

include ../Makefile.com
include ../../../Makefile.lib.64

LIBS= $(DYNLIB1)

.KEEP_STATE:

install: all $(ROOTLIBS64) $(ROOTLINKS64)
