#
#ident  "@(#)Makefile	1.1    96/03/29 SMI"
#
# Copyright (c) 1996, by Sun Microsystems, Inc.
# All rights reserved.
#
# Solaris boot/configuration assistant package makefile
#
clean clobber:
	$(RM) protoinfo pkginfo
