#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#
#pragma ident "@(#)Makefile	1.1 97/10/27 SMI"
#
# lib/fn/address/onc_fn_nisplus/sparcv9/Makefile
#

include ../Makefile.com
include ../../../../Makefile.lib.64

.KEEP_STATE:

BUILDCCC.SO += $(CCFLAGS)

debug install tcov: $(ROOTLIBDIR64) $(ROOTLIBS64)
