#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile.targ	1.1	99/01/25 SMI"
#
# lib/libnisdb/spec/Makefile.targ

LIBRARY	=	libnisdb.a
VERS	=	.2

OBJECTS	=	nisdb.o

SPECCPP =
