#
#ident  "@(#)Makefile 1.11     94/10/14 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
#
# lib/libthread_db/i386/Makefile
#

#CC=/usr/dist/local/share/sunpro,v2.0.1/sol-2.i386/bin/cc

include ../common/Makefile.common
