#
#ident	"@(#)Makefile	1.2	98/03/23 SMI"
#
# Copyright (c) 1995 by Sun Microsystems, Inc.
# All rights reserved.
#

include		../Makefile.com

.KEEP_STATE:

all:		$(OBJDIR) .WAIT $(PROG)

# DEMO DELETE START

install:	all $(ROOTONLDBINPROG)

lint:		$(LINTOUT)

# DEMO DELETE END

include		../Makefile.targ
