#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident   "@(#)Makefile 1.1     98/01/10 SMI"
#
# usr/src/cmd/cmd-inet/usr.sbin/in.named/named/tools/nsupdate/i386

include ../../../../../../Makefile.cmd

include ../Makefile.com

include ../../../../../../Makefile.targ
.KEEP_STATE:

all: $(PROG)

debug install: all $(ROOTUSRSBINPROG) $(ROOTLINKS) $(ROOTLINT)

