#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile.targ	1.1	99/01/25 SMI"
#
# lib/libsched/spec/Makefile.targ

LIBRARY	=	libsched.a
VERS	=	.1

OBJECTS	=	sched.o

SPECCPP =
