/*
 * Copyright (c) 1999 by Sun Microsystems, Inc.
 * All rights reserved.
 */

#pragma ident	"@(#)confunix.c	1.10	99/10/05 SMI"

/* Boot configuration. This file generated by config(8) */

#include <sys/bootconf.h>

struct bootobj rootfs = {
	{ { "" },	{ "sd3a" } }
};

struct bootobj swapfile = {
	{ { "" },	{ "" } }
};

struct bootobj frontfs = {
	{ { "" },	{ "" } }
};

struct bootobj backfs = {
	{ { "" },	{ "" } }
};
