#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)rtld.sparc64.msg	1.1	99/06/04 SMI"

@ _START_

# Message file for cmd/sgs/rtld (ld.so.1) - 64bit sparc specific.

@ MSG_REL_EXTND_PLTREF	"relocation error: %s: unable to process extended \
			 plt entry .plt[%lld]"

@ _END_

@ MSG_PTH_SP64_RTLD	"/usr/lib/sparcv9/ld.so.1"
@ MSG_PTH_SP64_USRLIB	"/usr/lib/sparcv9"
@ MSG_PTH_SP64_USRLIBSE	"/usr/lib/secure/sparcv9"

@ MSG_FIL_SP64_LDPROF	"/usr/lib/link_audit/sparcv9/ldprof.so.1"

@ MSG_LD_LIBPATH_64	"LIBRARY_PATH_64="

@ MSG_SYM_LAV9PLTENTER	"la_sparcv9_pltenter"
