#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)rtld.intel.msg	1.1	99/06/04 SMI"

@ _START_

# Message file for cmd/sgs/rtld (ld.so.1) - intel specific.

@ MSG_REL_RELOFF	"non-aligned relocation offset"
@ MSG_REL_UNSUPSZ	"relocation error: %s: file %s: symbol %s: \
			 offset size (%d bytes) is not supported"

@ _END_

@ MSG_SYM_CTYPE		"__ctype"
@ MSG_SYM_IOB		"__iob"
@ MSG_SYM_PLT		"_PROCEDURE_LINKAGE_TABLE_"
