#
#ident	"@(#)Makefile	1.1	99/03/29 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# pkgdefs/SUNWdhcm/Makefile
#

include ../Makefile.com

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
