#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile.sparcv7	1.1	99/08/11 SMI"

ROOTMOD = $(ROOT)/usr/lib/mdb/$(MDBTGT)

$(ROOTMOD)/%: %
	$(INS.file)

CCVERBOSE = -v
CFLAGS += $(CCVERBOSE) -xstrconst
LINTFLAGS = -xerroff=E_BAD_FORMAT_STR2

LFLAGS = -t -v
YFLAGS = -d -v
