#
#ident	"@(#)Makefile	1.1	97/05/30 SMI"
#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/setuname/sparc/Makefile

.KEEP_STATE:

include ../Makefile.com

install: all $(ROOTPROG32)
