#
#ident	"@(#)Makefile	1.1	99/10/08 SMI"
#
# lib/zlib/sparc/Makefile

MAPDIR=	../spec/sparc

include ../Makefile.com

.KEEP_STATE:

all: $(LIBS)

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT) install_src
