#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident "@(#)Makefile	1.4 97/11/20 SMI"
#
# lib/fn/libxfn.1/sparc/Makefile
#

include ../Makefile.com

.KEEP_STATE:

install debug tcov: $(ROOTLIBDIR) $(ROOTLIBS)
