#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	99/08/11 SMI"

MODULE = krtld.so
MDBTGT = kvm

MODSRCS = krtld.c

include ../../../../Makefile.cmd
include ../../Makefile.sparcv7
include ../../../Makefile.module
