#
#ident	"@(#)Makefile	1.2	90/07/05 SMI"
#
# Copyright (c) 1990 by Sun Microsystems, Inc.
#

PROG= from

include ../Makefile.ucbcmd

FILEMODE=	755

.KEEP_STATE:

all: $(PROG) 

install: all $(ROOTPROG)

clean:

lint:	lint_PROG

include ../Makefile.ucbtarg
