#
#	Copyright (c) 1996 by Sun Microsystems, Inc.
#	All rights reserved.
#
#ident	"@(#)Makefile	1.6	98/01/05 SMI"
#

include		$(SRC)/cmd/sgs/liblddbg/Makefile.com

.KEEP_STATE:

all:		$(DYNLIB) $(LIBLINKS)

install:	all $(ROOTDYNLIB)

include		$(SRC)/cmd/sgs/liblddbg/Makefile.targ
