#ident "@(#)Makefile	1.1	97/11/09 SMI"
#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#
# cmd/syslogd/sparcv9/Makefile

include ../Makefile.com
include ../../Makefile.cmd.64

all: $(PROG)

install: all $(ROOTUSRSBINPROG64)
