#
#ident	"@(#)Makefile	1.1	91/05/04 SMI"
#

PROG= expr

include ../Makefile.ucbcmd

FILEMODE=	755

.KEEP_STATE:

all: $(PROG) 

install: all $(ROOTPROG)

clean:

lint:	lint_PROG

include ../Makefile.ucbtarg
