#
#pragma ident	"@(#)Makefile	1.2	99/08/25 SMI"
#
# Copyright (c) 1991-1999 by Sun Microsystems, Inc.
# All rights reserved
#

include ../Makefile.com

DATAFILES += i.initd i.preserve i.ncalogd i.ncakmod depend

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
