#
#pragma ident	"@(#)Makefile	1.1	99/05/04 SMI"
#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libxcurses/ia64/Makefile

MAPDIR=	../spec/ia64
include ../Makefile.com
include ../../Makefile.lib.64

.KEEP_STATE:

all: $(LIBS)

install: all $(ROOTLIBS64) $(ROOTLINKS64) $(ROOTLINT64)
