#
# Copyright (c) 1990,1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.20	99/01/25 SMI"
#
# lib/librt/sparc/Makefile

MAPDIR=	../spec/sparc
include ../Makefile.com

.KEEP_STATE:

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
