#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.
#
# ident	"@(#)data.msg	1.4	97/05/08 SMI"
#
# Message file for cmd/sgs/libconv/common/data.c

@ MSG_DATA_BYTE		"BYTE"
@ MSG_DATA_ADDR		"ADDR"
@ MSG_DATA_DYN		"DYN"
@ MSG_DATA_EHDR		"EHDR"
@ MSG_DATA_HALF		"HALF"
@ MSG_DATA_OFF		"OFF"
@ MSG_DATA_PHDR		"PHDR"
@ MSG_DATA_RELA		"RELA"
@ MSG_DATA_REL		"REL"
@ MSG_DATA_SHDR		"SHDR"
@ MSG_DATA_SWORD	"SWORD"
@ MSG_DATA_SYM		"SYM"
@ MSG_DATA_WORD		"WORD"
@ MSG_DATA_VDEF		"VDEF"
@ MSG_DATA_VNEED	"VNEED"
@ MSG_DATA_SXWORD	"SXWORD"
@ MSG_DATA_XWORD	"XWORD"
