#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.
#
# ident	"@(#)phdr.msg	1.3	99/06/01 SMI"
#
# Message file for cmd/sgs/libconv/common/dl.c

@ MSG_PT_NULL		"[ PT_NULL ]"
@ MSG_PT_LOAD		"[ PT_LOAD ]"
@ MSG_PT_DYNAMIC	"[ PT_DYNAMIC ]"
@ MSG_PT_INTERP		"[ PT_INTERP ]"
@ MSG_PT_NOTE		"[ PT_NOTE ]"
@ MSG_PT_SHLIB		"[ PT_SHLIB ]"
@ MSG_PT_PHDR		"[ PT_PHDR ]"

@ MSG_PT_IA64_ARCHEXT	"[ PT_IA_64_ARCHEXT ]"
@ MSG_PT_IA64_UNWIND	"[ PT_IA_64_UNWIND ]"

@ MSG_PF_X		 " PF_X "
@ MSG_PF_W		 " PF_W "
@ MSG_PF_R		 " PF_R "

@ MSG_GBL_ZERO		"0"
@ MSG_GBL_OSQBRKT	"["
@ MSG_GBL_CSQBRKT	"]"
