#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.
#
# ident	"@(#)relocate_i386.msg	1.2	96/02/26 SMI"
#
# Message file for cmd/sgs/libconv/i386/relocate.c

@ MSG_R_386_NONE	"R_386_NONE"
@ MSG_R_386_32		"R_386_32"
@ MSG_R_386_PC32	"R_386_PC32"
@ MSG_R_386_GOT32	"R_386_GOT32"
@ MSG_R_386_PLT32	"R_386_PLT32"
@ MSG_R_386_COPY	"R_386_COPY"
@ MSG_R_386_GLOB_DAT	"R_386_GLOB_DAT"
@ MSG_R_386_JMP_SLOT	"R_386_JMP_SLOT"
@ MSG_R_386_RELATIVE	"R_386_RELATIVE"
@ MSG_R_386_GOTOFF	"R_386_GOTOFF"
@ MSG_R_386_GOTPC	"R_386_GOTPC"
@ MSG_R_386_32PLT	"R_386_32PLT"
