#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.
#
# ident	"@(#)segments.msg	1.3	96/04/26 SMI"
#
# Message file for cmd/sgs/libconv/common/segments.c

@ MSG_FLG_SG_VADDR	" FLG_SG_VADDR "
@ MSG_FLG_SG_PADDR	" FLG_SG_PADDR "
@ MSG_FLG_SG_LENGTH	" FLG_SG_LENGTH "
@ MSG_FLG_SG_ALIGN	" FLG_SG_ALIGN "
@ MSG_FLG_SG_ROUND	" FLG_SG_ROUND "
@ MSG_FLG_SG_FLAGS	" FLG_SG_FLAGS "
@ MSG_FLG_SG_TYPE	" FLG_SG_TYPE "
@ MSG_FLG_SG_ORDER	" FLG_SG_ORDER "
@ MSG_FLG_SG_EMPTY	" FLG_SG_EMPTY "
@ MSG_FLG_SG_NOHDR	" FLG_SG_NOHDR "

@ MSG_GBL_ZERO		"0"
@ MSG_GBL_OSQBRKT	"["
@ MSG_GBL_CSQBRKT	"]"
