#
# Copyright (c) 1998 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)symbols.msg	1.5	98/08/28 SMI"
#
# Message file for cmd/sgs/libconv/common/symbols.c

@ MSG_STT_NOTYPE	"NOTY"
@ MSG_STT_OBJECT	"OBJT"
@ MSG_STT_FUNC		"FUNC"
@ MSG_STT_SECTION	"SECT"
@ MSG_STT_FILE		"FILE"
@ MSG_STT_REGISTER	"REGI"

@ MSG_STB_LOCAL		"LOCL"
@ MSG_STB_GLOBAL	"GLOB"
@ MSG_STB_WEAK		"WEAK"

@ MSG_SHN_UNDEF		"UNDEF"
@ MSG_SHN_ABS		"ABS"
@ MSG_SHN_COMMON	"COMMON"

@ MSG_FMT_VAL		"0x%8.8llx"
@ MSG_FMT_VAL_64	"0x%12.12llx"
