#
#ident	"@(#)Makefile	1.1	99/03/31 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.

PROG= coreadm

include ../Makefile.cmd

.KEEP_STATE:

CFLAGS += -v

all: $(PROG)

install: all $(ROOTPROG)

clean:

lint:	lint_PROG

include ../Makefile.targ
