#
#ident	"@(#)Makefile	1.3	99/03/30 SMI"
#
# Copyright (c) 1995,1998 by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/eeprom/common/Makefile
#
include ../../Makefile.cmd

PROG		= eeprom
FILEMODE	= 555
GROUP		= sys

.KEEP_STATE:

all install : $(ROOTUSRSBINPROG)

clean clobber : FRC
	$(RM) $(ROOTUSRSBINPROG)

FRC:
