#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile.targ	1.1	99/07/18 SMI"
#
# lib/krb5/kadm5/clnt/spec/Makefile.targ

LIBRARY	=	libkadm5clnt.a
VERS	=	.1

OBJECTS	=	kadm5clnt.o
