#
#ident	"@(#)Makefile	1.1	97/11/09 SMI"
#
# Copyright (c) 1995 - 1997, by Sun Microsystems, Inc.
# All rights reserved.
#

include ../Makefile.com

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
