#
#ident	"@(#)Makefile	1.2	96/03/18 SMI"
#
# Copyright (c) 1993, Sun Microsystems, Inc.
#

PROG= dumpcs

include ../Makefile.cmd

.KEEP_STATE:

all: $(PROG)

install : all $(ROOTPROG)

clean:

lint:	lint_PROG

include ../Makefile.targ
