#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident "@(#)Makefile	1.1 97/10/20 SMI"
#
# lib/fn/address/onc_fn_nisplus_root/sparc/Makefile
#

include ../Makefile.com

install debug tcov: $(ROOTLIBDIR) $(ROOTLIBS) $(ROOTFNLINKS)

.KEEP_STATE:

