#
#ident	"@(#)Makefile	1.1	99/08/13 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.

include		$(SRC)/cmd/sgs/libcrle/Makefile.com

.KEEP_STATE:

all:		$(DYNLIB) $(LIBLINKS)

install:	all $(ROOTDYNLIB)

lint:		$(LINTOUT32) $(SGSLINTOUT)

include		$(SRC)/cmd/sgs/libcrle/Makefile.targ
