#
#ident	"@(#)Makefile	1.1	93/06/10 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
#
# cmd/sgs/lorder/Makefile
#

PROG=		lorder

SRCS=		$(PROG:%=%.sh

include 	../../Makefile.cmd

.KEEP_STATE:

all:		$(PROG)

install:	all $(ROOTCCSBINPROG)

clean:

lint:

include		../../Makefile.targ
