#
# Copyright (c) 1991 by Sun Microsystems, Inc.
#

#ident	"@(#)Makefile	1.8	93/07/19 SMI"

#
# The common makefile does all the work; this makefile is here to give the NSE
# a private place to record dependencies.
#

# this deliberately avoids macro names ARCH and KERNARCH for local control
KARCH= sun4d

MMU=	srmmu

include ../Makefile.com
