#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile.targ	1.1	99/01/25 SMI"
#
# lib/libplot/plot/spec/Makefile.targ

LIBRARY	=	libplot.a
VERS	=	.1

OBJECTS	=	plot.o

TRANSCPP =
SPECCPP =
