#
#ident	"@(#)Makefile	1.1	90/07/03 SMI"
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#

PROG= whereis

include ../Makefile.ucbcmd

FILEMODE=	755

.KEEP_STATE:

all: $(PROG)

install: all $(ROOTPROG)

clean:

lint:	lint_PROG

include ../Makefile.ucbtarg
