#
#ident	"@(#)Makefile	1.1	99/10/08 SMI"

# cmd/bzip2/sparc/Makefile

MAPDIR= ../spec/sparc

include ../Makefile.com

all: $(DYNLIB) $(PROG1) $(PROG2) $(PROG1LINK1) $(PROG1LINK2)

install: all $(ROOTLIBS) $(ROOTPROG) $(ROOTBIN)/$(PROG1LINK1) \
	$(ROOTBIN)/$(PROG1LINK2) $(ROOTLINKS) $(ROOTLINT)
