#
# Copyright (c) 1993, 1997 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.2	97/12/08 SMI"

include ../Makefile.com

DATAFILES += depend i.preserve i.initd

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
