#
#ident  "@(#)Makefile	1.1	99/04/02 SMI"
#
# Copyright (c) 1998, by Sun Microsystems, Inc.
# All rights reserved.
#

MAPDIR= ../spec/i386

include ../Makefile.com

.KEEP_STATE:

all: $(LIBS)

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
