#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#
#pragma ident	"@(#)Makefile	1.1	99/05/04 SMI"
#
# lib/fn/context/x500/libldap/ia64/Makefile
#

include ../Makefile.com
include ../../../../../Makefile.lib.64

.KEEP_STATE:

#BUILD.SO += $(CFLAGS)

debug install tcov: all $(ROOTLIBDIR64) $(ROOTLINKS64)
