#
#	Copyright (c) 1996 by Sun Microsystems, Inc.
#	All rights reserved.
#
#ident	"@(#)Makefile	1.1	96/03/15 SMI"
#
# Makefile for sgs/message/i386

include		$(SRC)/cmd/sgs/messages/Makefile.com

.KEEP_STATE:

include		$(SRC)/cmd/sgs/messages/Makefile.targ
