#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.1	99/05/04 SMI"

include		$(SRC)/cmd/sgs/0@0/Makefile.com

.KEEP_STATE:

install:	all $(ROOTLIBDIR64)/$(DYNLIB)

include		$(SRC)/cmd/sgs/0@0/Makefile.targ
include		../../Makefile.sub.64

