#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.1	99/05/14 SMI"
#
# cmd/abi/ldcullstabs/i386/Makefile
#

include	../Makefile.lib
include	$(SRC)/lib/Makefile.lib
include	../Makefile.com

install: all $(ROOTABILIB)
