#
# Copyright (c) 1996-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.3	99/01/25 SMI"
#
# lib/libdevid/i386/Makefile

MAPDIR=	../spec/i386
include ../Makefile.com

DYNFLAGS += $(DYNFLAGS32)

all: $(LIBS)

.KEEP_STATE:

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
