#
#ident	"@(#)Makefile	1.1	95/10/04 SMI"
#
# Copyright (c) 1994 by Sun Microsystems, Inc.
#

include ../Makefile.com

DATAFILES += depend

.KEEP_STATE:

all: $(FILES)

install: all pkg

include ../Makefile.targ
