#
#pragma ident	"@(#)Makefile	1.1	94/03/22 SMI"
#
# Copyright (c) 1994 by Sun Microsystems, Inc.
#

PROG= rtc

include ../Makefile.cmd

all:	$(PROG)

install: all $(ROOTUSRSBIN)/$(PROG)


FRC:

clean:

include ../Makefile.targ
