#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.4	99/01/25 SMI"
#
# lib/libkstat/sparcv9/Makefile

MAPDIR=	../spec/sparcv9

include ../Makefile.com
include ../../Makefile.lib.64

LIBS=	$(DYNLIB) $(LINTLIB)

.KEEP_STATE:

all: $(LIBS) 

install: all $(ROOTLIBS64) $(ROOTLINKS64)
