#
#ident	"@(#)Makefile	1.1	97/11/09 SMI"
#
# Copyright (c) 1997 by Sun Microsystems, Inc.
#

include ../Makefile.com

.KEEP_STATE:

DATAFILES += depend

all: $(FILES)
install: all pkg

include ../Makefile.targ
