#
# ident	"@(#)Makefile	1.1	99/07/02 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libmd5/spec/sparc/Makefile
#

include ../Makefile.targ

# Add arch specific objects here
OBJECTS +=

include $(SRC)/lib/Makefile.lib

# Uncomment the following if the linker complains
#sparc_C_PICFLAGS  = -K PIC

include $(SRC)/lib/Makefile.spec

.KEEP_STATE:

install: $(ROOTABILIB)
