#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	99/05/24 SMI"

FSTYPE=		cachefs
LIBPROG=	dfshares
SRCS=		dfshares.sh

include		../../Makefile.fstype

all:		$(LIBPROG)

install:	all

clean:
	$(RM) $(LIBPROG)
