#
# ident	"@(#)Makefile	1.6	99/04/20 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
 
include ../Makefile.com

DATAFILES += depend

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
