#
#ident	"@(#)Makefile	1.2	93/09/15 SMI"
#
# Copyright (c) 1990 by Sun Microsystems, Inc.
#
# cmd/adb/sparc/kadb/sun4/Makefile
#
# The common makefile does all the work; this makefile is here to give the NSE
# a private place to record dependencies.
#

# this deliberately avoids macro names ARCH and KERNARCH for local control
ARCH=  i86pc
KARCH= i386

include ../Makefile.com
