#
#ident	@(#)Makefile	1.1	96/03/23 (c) Sun Microsystems, Inc.
#
# Copyright (c) 1996 by Sun Microsystems, Inc.
#		All Rights Reserved
#

include ../Makefile.com

DATAFILES += depend

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
