#
# Copyright (c) 1998, by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libsecdb/sparcv9/Makefile
#
#"@(#)Makefile	1.1	99/07/12 SMI"
#

MAPDIR=	../spec/sparcv9

include ../Makefile.com
include ../../Makefile.lib.64

.KEEP_STATE:

LIBS = 	$(DYNLIB) $(LINTLIB)

all: $(LIBS)

install: all $(ROOTLIBS64) $(ROOTLINKS64)
