#
#ident	"@(#)Makefile	1.4	97/07/21 SMI"
#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/tnf/prex/sparcv9/Makefile

include ../Makefile.com
include ../../../Makefile.cmd.64
CFLAGS64 += -I.. -I.
LINTFLAGS64 += -I.. -I.
prexgram.o prexlex.o := CCVERBOSE=

install: all $(ROOTPROG64)
