#
#ident	"@(#)Makefile	1.3	99/01/21 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#

include ../Makefile.com


.KEEP_STATE:

all:		$(DYNLIB) $(LIBLINKS)
install:	all $(ROOTDYNLIB) $(ROOTLINKS) $(ROOTLIBDIR)/$(LINTLIB) \
		$(ROOTLIBDIR)/$(LINTLIBSRC)

include ../Makefile.targ
