#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#
#pragma ident "@(#)Makefile	1.1 97/10/27 SMI"
#
# lib/fn/context/nisplus_root/sparc/Makefile
#

include ../Makefile.com

.KEEP_STATE:

debug install tcov: $(ROOTLIBDIR) $(ROOTLIBS)
