#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.7	97/11/04 SMI"
#
# lib/gss_mechs/mech_dummy/i386/Makefile

include ../Makefile.com

LIBS += $(DYNLIB)

.KEEP_STATE:

all: $(LIBS)

install: all $(ROOTLIBS) $(ROOTLINKS)
