#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.1	99/05/04 SMI"
#

MAPDIR=	../spec/ia64

include ../Makefile.com
include ../../../Makefile.lib.64

.KEEP_STATE:

BUILDCCC.SO += $(CCFLAGS)

install debug tcov: $(ROOTLIBDIR64) \
      $(ROOTLIBS64) $(ROOTLINKSCCC64)
