#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile.targ	1.2	99/05/14 SMI"
#
# lib/nametoaddr/straddr/spec/Makefile.targ

LIBRARY	=	straddr.a
VERS	=	.2

OBJECTS	=	straddr.o

TRANSCPP =
SPECCPP =
