#
# Copyright (c) 1993-1997 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.4	99/07/07 SMI"

include ../Makefile.com

DATAFILES += i.initd i.powerconf

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
