#
#ident	"@(#)Makefile	1.1	95/06/30 SMI"
#
# Copyright (c) 1991-1994, Sun Microsystems, Inc.
#
# psm/stand/boot/i386/promif/boot/Makefile
#

TOPDIR	=	../../../../../../..
CPPDEFS =	-DKADB -D_KADB

include ../../Makefile.com
