#
# "@(#)Makefile.backup 1.14     99/03/30 SMI"
#
# Copyright (c) 1993,1998 by Sun Microsystems, Inc.
#
# cmd/backup/Makefile.backup
#

include $(SRC)/cmd/Makefile.cmd

# xxx should pass -Nlevel=4 (takes 62 minutes of cpu for lib and dump)
LINTFLAGS=	-errchk=%all,longptr64 -errhdr=%user -F -m \
		-Ncheck=%all,no%extern -Nlevel=3 -Xtransition=yes \
		-errtags=yes -erroff=E_UNCAL_F,E_ASGN_RESET -s
# -c: continuation line indentation (broken for multi-line continuations)
# -h: heuristic checks (sometimes wrong)
# -p: extra-picky
# -v: verbose
# -C: ignore header block comments
# -P: check for non-POSIX types
#CSTYLEFLAGS=	-c -h -p -v -P
CSTYLEFLAGS=	-h -p -P

UFSROOTETC=		$(ROOT)/etc
UFSROOTUSR=		$(ROOT)/usr
UFSROOTUSRLIB=		$(UFSROOTUSR)/lib
UFSROOTUSRLIBFS=	$(UFSROOTUSRLIB)/fs
UFSROOTUSRLIBFSTYPE=	$(UFSROOTUSRLIBFS)/$(FSTYPE)
UFSROOTUSRSBIN=		$(UFSROOTUSR)/sbin

$(CH)$(UFSROOTETC)	:= DIRMODE = 755
$(UFSROOTETC)		:= OWNER   = root
$(UFSROOTETC)		:= GROUP   = sys
$(CH)$(UFSROOTUSR)	:= DIRMODE = 755
$(UFSROOTUSR)		:= OWNER   = root
$(UFSROOTUSR)		:= GROUP   = bin
$(CH)$(UFSROOTUSRLIB)	:= DIRMODE = 755
$(UFSROOTUSRLIB)	:= OWNER   = root
$(UFSROOTUSRLIB)	:= GROUP   = bin
$(CH)$(UFSROOTUSRLIBFS)	:= DIRMODE = 755
$(UFSROOTUSRLIBFS)	:= OWNER   = root
$(UFSROOTUSRLIBFS)	:= GROUP   = sys
$(CH)$(UFSROOTUSRLIBFSFSTYPE):= DIRMODE = 755
$(UFSROOTUSRLIBFSFSTYPE):= OWNER   = root
$(UFSROOTUSRLIBFSFSTYPE):= GROUP   = sys
$(CH)$(UFSROOTUSRSBIN)	:= DIRMODE = 755
$(UFSROOTUSRSBIN)	:= OWNER   = root
$(UFSROOTUSRSBIN)	:= GROUP   = bin

UFSROOTPKGUSRLIBFSTYPE=	$(PROG:%=$(UFSROOTUSRLIBFSTYPE)/%)
UFSROOTPKGETC=		$(PROT:%=$(UFSROOTETC)/%)

$(UFSROOTETC)/%: $(UFSROOTETC) %
	$(INS.file)

$(UFSROOTUSRLIBFSTYPE)/%: $(UFSROOTUSRLIBFSTYPE) %
	$(INS.file)

# set up TARGET macro for all Makefile here
all:=		TARGET= all
install:=	TARGET= install
clean:=		TARGET= clean
clobber:=	TARGET= clobber
lint:=		TARGET= lint
debug:=		TARGET= debug
check:=		TARGET= check
_msg:=		TARGET= _msg

# default dump library is the -O one
DUMPLIB=	libdump.a

# define the DO_SUBDIR macro, so that it can be changed here for all Makefiles
DO_SUBDIR=	cd $@; pwd; $(MAKE)  \
			LINTFLAGS="$(LINTFLAGS)" $(TARGET)
DO_LIBDIR=	@cd $(@D); pwd; $(MAKE) LINTFLAGS="$(LINTFLAGS)" $(TARGET)
