#
# Copyright (c) 1995 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	95/03/01 SMI"

PROG=		ranlib

SRCS=		$(PROG:%=%.sh

include 	../../Makefile.cmd

.KEEP_STATE:

all:		$(PROG)

install:	all $(ROOTCCSBINPROG)

clean:

lint:

include		../../Makefile.targ
