#ident	"@(#)Makefile.targ	1.1	99/01/25 SMI"
#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libsocket/spec/Makefile.targ

LIBRARY	=	libsocket.a
VERS	=	.1

OBJECTS	=	socket.o	\
		svr4msg.o	\
		xpgmsg.o

SPECCPP =	-I..
