#
#ident	"@(#)Makefile	1.6	93/11/12 SMI"
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#

PROG= pt_chmod

include ../Makefile.cmd

FILEMODE= 04111
OWNER= root

.KEEP_STATE:

all: $(PROG) 

install: all $(ROOTLIBPROG)

clean:

lint:	lint_PROG

include ../Makefile.targ
