# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident  "@(#)Makefile   1.1     97/09/04 SMI"
#
# lib/fn/libfn_spf/sparc/Makefile
#

include ../Makefile.com

.KEEP_STATE:

install debug tcov: $(ROOTLIBDIR) $(ROOTLIBS) \
	$(ROOTLINKSCCC) $(ROOTFNLINKS)


