#
#ident	"@(#)Makefile	1.3	99/03/21 SMI"
#
# Copyright (c) 1996 by Sun Microsystems, Inc.
#

include ../Makefile.com


DATAFILES += depend i.preserve i.publickey i.ypnicknames

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
