#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident   "@(#)Makefile 1.1     97/12/03 SMI"
#
# usr/src/cmd/cmd-inet/usr.sbin/in.named/named-xfer/sparc

include ../../../../../Makefile.cmd

include ../Makefile.com

.KEEP_STATE:

all: $(PROG)

debug install: all $(ROOTUSRSBINPROG) $(ROOTLINKS) $(ROOTLINT)
