#
#ident	"@(#)Makefile	1.1	99/04/08 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
#

include ../Makefile.com

DATAFILES +=

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
