#!/sbin/sh
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#

#
# postinstall script for SUNWrmodr package.
#
#ident "@(#)postinstall 1.1 99/04/08"
#
#
	
devconf_updates()
{
	#
	# Probe always BEFs were re-arranged.  This eliminated the
	# previously existing drivers/isa.{050,075,088}. It also
	# cause pe3.bef to be moved out of isa.025
	#
	# A later rearrangement (11/96) caused ata.bef to be moved
	# out of isa.025 as well.
	#
	#
	MVDBEF3=/boot/solaris/drivers/isa.025/ata.bef
	MVDBEF5=/boot/solaris/drivers/isa.125/elx.bef

	DELDIR1=/boot/solaris/drivers/isa.050
	DELDIR2=/boot/solaris/drivers/isa.075
	DELDIR3=/boot/solaris/drivers/isa.088

	if [ -f ${BASEDIR}/${MVDBEF1} ]
	then
		rm -f ${BASEDIR}/${MVDBEF1}
	fi 

	if [ -f ${BASEDIR}/${MVDBEF2} ]
	then
		rm -f ${BASEDIR}/${MVDBEF2}
	fi 

	if [ -f ${BASEDIR}/${MVDBEF3} ]
	then
		rm -f ${BASEDIR}/${MVDBEF3}
	fi 

	if [ -f ${BASEDIR}/${MVDBEF4} ]
	then
		rm -f ${BASEDIR}/${MVDBEF4}
	fi 

	if [ -f ${BASEDIR}/${MVDBEF5} ]
	then
		rm -f ${BASEDIR}/${MVDBEF5}
	fi 

	if [ -d ${BASEDIR}/${DELDIR1} ]
	then
		rm -rf ${BASEDIR}/${DELDIR1}
	fi

	if [ -d ${BASEDIR}/${DELDIR2} ]
	then
		rm -rf ${BASEDIR}/${DELDIR2}
	fi

	if [ -d ${BASEDIR}/${DELDIR3} ]
	then
		rm -rf ${BASEDIR}/${DELDIR3}
	fi

}


# Platform-specific drivers
case "${ARCH}" in
i386)
	devconf_updates

	#
	# remove the old boot entries from the package database
	#
	OLDBOOT=/platform/i86pc/boot
	OLDBOOTDIR=${BASEDIR}${OLDBOOT}
	#
	# update the package database only when the directory
	# /platform/i86pc/boot/solaris exists but it is not
	# symbolic link 
	#
	if [ ! -h ${OLDBOOTDIR}/solaris -a -d ${OLDBOOTDIR}/solaris ] ;
	then
		removef $PKGINST $OLDBOOT/solaris/*/*/* > /dev/null 2>&1
		removef $PKGINST $OLDBOOT/solaris/*/* > /dev/null 2>&1
		removef $PKGINST $OLDBOOT/solaris/* > /dev/null 2>&1
		removef	$PKGINST $OLDBOOT/* > /dev/null 2>&1
		removef $PKGINST $OLDBOOT > /dev/null 2>&1
		rm -rf $OLDBOOTDIR >/dev/null 2>&1
		removef -f $PKGINST > /dev/null 2>&1
	fi

	#
	# this is a workaround for the install bug #4105232
	# install needs to update the bootpath in bootenv.rc and hardcodes 
	# the path for bootenv.rc to /platform/i86pc/boot/solaris
	# once this bug is fixed, the following lines can be deleted 
	# 
	OLDBOOTDIR=${BASEDIR}/platform/i86pc/boot
	if [ -d ${OLDBOOTDIR} ] ;
	then
		rm -rf ${OLDBOOTDIR} >/dev/null 2>&1
	fi
	mkdir -p ${OLDBOOTDIR} >/dev/null 2>&1
	ln -s ../../../boot/solaris ${OLDBOOTDIR}/solaris >/dev/null 2>&1
	#
	# End of workaround
	#
	
	;;
esac

exit 0
