#
# Copyright (c) 1995,1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile.targ	1.3	99/01/25 SMI"
#
# lib/libsys/Makefile.targ

pics/%.o:	%.s
		$(COMPILE.s) -o $@ $<
		$(POST_PROCESS_O)

pics/%.o:	%.c
		$(COMPILE.c) -o $@ $<
		$(POST_PROCESS_O)

$(DYNLIB):	$(MAPFILES)

$(MAPFILE):
	@cd $(MAPDIR); $(MAKE) mapfile

include		../../../lib/Makefile.targ

FRC:
