#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/prstat/sparc/Makefile
#

#ident	"@(#)Makefile	1.1	99/04/22 SMI"

.KEEP_STATE:

include ../Makefile.com

install: all $(ROOTPROG32)
