#
#ident	"@(#)Makefile	1.1	99/10/08 SMI"
#
# cmd/bzip2/sparcv9/Makefile

MAPDIR=../spec/sparcv9

include ../Makefile.com
include ../../Makefile.cmd.64
include ../../../lib/Makefile.lib.64

all: $(DYNLIB)

install: all $(ROOTLIBS64) $(ROOTLINKS64) $(ROOTLINT64)
