#
# Copyright (c) 1992-1995, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident  "@(#)Makefile.objs 1.5     95/09/19 SMI"

SCHOBJECTS= rhosts_auth.o

DEFOBJECTS=$(SCHOBJECTS:%=def_%)

DEFOBJS=$(DEFOBJECTS:%=objs/%)

DEFPICS=$(DEFOBJECTS:%=pics/%)

