#
#ident	"@(#)Makefile	1.5	92/07/14 SMI"
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#

# XXX - this component has gotten too small to be real, and should be
#	removed. The system file should be installed from somewhere
#	else.

PROG= system

include ../Makefile.cmd

FILEMODE= 0644
OWNER= root
GROUP= sys

.KEEP_STATE:

all: $(PROG)

install: all $(ROOTETCPROG)

clean:

lint:

clobber:
