#
# Copyright (c) 1997 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.5	97/07/21 SMI"
#

include ../Makefile.com
include ../../Makefile.cmd.64

CFLAGS64 += -D_ELF64

install: all $(ROOTUSRSBINPROG64)
