#
#ident	"@(#)Makefile	1.2	92/12/15 SMI"
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#

PROG= nlsadmin

include ../Makefile.cmd

OWNER= root
GROUP= adm
FILEMODE= 0755

.KEEP_STATE:

all: $(PROG) 

install: all $(ROOTUSRSBINPROG)

clean:

lint:	lint_PROG

include ../Makefile.targ
