#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#
# lib/fn/address/onc_fn_nis/i386/Makefile
#

include ../Makefile.com

.KEEP_STATE:

debug install tcov: $(ROOTLIBDIR) $(ROOTLIBS)
