#
#ident	"@(#)Makefile	1.5	99/08/26 SMI"
#
# Copyright (c) 1996, by Sun Microsystems, Inc.
# All rights reserved.

include ../Makefile.com

.KEEP_STATE:

DATAFILES += i.preserve

all: $(FILES) $(MACHDATAFILES)
install: all pkg

include ../Makefile.targ
