#
#ident	"@(#)Makefile	1.11	97/05/30 SMI"
#
# Copyright (c) 1990, 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/ipcrm/Makefile
#

include ../Makefile.cmd

PROG=		ipcrm

LINTFLAGS =	-x

.KEEP_STATE:

all: 		$(PROG) 

install:	all $(ROOTPROG)

clean:

lint:	lint_PROG

include ../Makefile.targ
