#
#ident	"@(#)Makefile	1.4	94/07/08 SMI"
#
# Copyright (c) 1994 by Sun Microsystems, Inc.
#
#

include		../Makefile.sub

.KEEP_STATE:

#
# Be default we do not install the libldmake.so.1 library into the $(ROOT)
# partition.  If this is required do the following:
#	% cd $(MACH); make -e install
#

install:=	TARGET= all
