#
#ident	"@(#)Makefile	1.2	96/03/18 SMI"
#
# Copyright (c) 1995 by Sun Microsystems, Inc.
#

PROG= asa

include ../Makefile.cmd

CFLAGS		+=	-v

.KEEP_STATE:

all: $(PROG) 

install: all $(ROOTPROG)

clean:

lint:	lint_PROG

include ../Makefile.targ
