#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.1	99/03/19 SMI"
#
# lib/cfgadm_plugins/scsi/spec/Makefile

include	$(SRC)/lib/Makefile.spec.arch
