#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.1	99/05/04 SMI"
#
# lib/nametoaddr/straddr/ia64/Makefile

MAPDIR=	../spec/ia64
include ../Makefile.com
include ../../../Makefile.lib.64

LIBS=	$(DYNLIB)

.KEEP_STATE:

install: all $(ROOTLIBS64) $(ROOTLINKS64)
