#
#ident	"@(#)Makefile	1.1	98/07/14 SMI"
#
# Copyright (c) 1998 by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/devfsadm/i386/Makefile
#

MISC_LINK_ISA = misc_link_i386


include ../Makefile.com

install: all
