#
#ident	"@(#)Makefile	1.3	92/12/16 SMI"
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#

PROG= du 

include ../Makefile.ucbcmd

FILEMODE=	755

.KEEP_STATE:

all: $(PROG) 

install: all $(ROOTPROG)

clean:

lint:

include ../Makefile.ucbtarg
