#
# Copyright (c) 1999, by Sun Microsystems, Inc.
# All rights reserved.
#
#
# lib/gss_mechs/mech_krb5/ia64/do/Makefile
#
#pragma ident	"@(#)Makefile	1.1	99/07/18 SMI"

KSUBDIR=do
include ../../Makefile.com
include ../../../../Makefile.lib.64

LIBS += $(DYNLIB)

.KEEP_STATE:

all: $(LIBS)

install: all $(ROOTLIBDIR) $(ROOTLIBS64) $(ROOTLINKS64)
