#
#pragma ident	"@(#)Makefile	1.2	98/04/09 SMI"
#
# Copyright (c) 1996-1997 by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/ldap/sparc/Makefile
#
include ../Makefile.com

.KEEP_STATE:

install: $(ALLPROG) $(ROOTPROG) $(ROOTLINKS) $(ROOTLINT)

FRC:
