$ *************************************<+>*************************************
$ *****************************************************************************
$ **
$ **  File:        pam_role.msg
$ **
$ **  Project:     pam
$ **
$ **  Description:
$ **  -----------
$ **  This file is the source for the pam_role message catalog.  
$ **
$ **  It contains messages for the pam_role service module (set 1).  
$ **
$ **
$ *****************************************************************************
$ **
$ **     (c) Copyright 1996 Sun Microsystems, Inc.
$ **     All Rights reserved
$ **
$ *****************************************************************************
$ *************************************<+>*************************************


$ role module messages 
$set 1

1 Roles can only be assumed by authorized users 
