#
#ident	"@(#)Makefile	1.1	94/12/10 SMI"
#
# Copyright (c) 1991-1994, Sun Microsystems, Inc.
#
# psm/stand/boot/i386/promif/boot/Makefile
#

TOPDIR	=	../../../../../..
CPPDEFS =	-DI386BOOT

include ../Makefile.com
