#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	99/10/06 SMI"
#
# lib/libldap/sparcv9/Makefile

MAPDIR=	../spec/sparcv9

include ../Makefile.com
include ../../Makefile.lib.64

LIBS = $(DYNLIB)

.KEEP_STATE:

all: $(LIBS)

install: all $(ROOTLIBS64)
