#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	99/08/11 SMI"

include ../../Makefile.common
SUBDIRS = mdb $(COMMON_MODULES)
include ../../Makefile.subdirs

.PARALLEL: $(SUBDIRS)
