#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident "@(#)Makefile 1.1	99/09/21 SMI"
#
# ucblib/libtermcap/spec/sparc/Makefile

.KEEP_STATE:

include	../Makefile.targ

# Add arch specific objects here
OBJECTS	+=

include	$(SRC)/lib/Makefile.lib

# Uncomment the following if the linker complains
#sparc_C_PICFLAGS  = -K PIC

include	$(SRC)/lib/Makefile.spec

install: $(UCBLIB_ABILIB)
