#
# ident	"@(#)Makefile.include	1.3	92/07/14 SMI"
#
# Copyright (c) 1990 by Sun Microsystems, Inc.
#
# cmd/osadmin/Makefile.include
#
# Included by subdirectories - global settings.

ROOTLBIN = $(ROOT)/usr/lbin

# install rule for targets in ROOTLBIN
$(ROOTLBIN)/%: %
	$(INS.file)
