#
#ident	"@(#)Makefile	1.1	99/10/08 SMI"
#
# lib/zlib/sparcv9/Makefile

MAPDIR=	../spec/sparcv9

include ../Makefile.com
include ../../Makefile.lib.64

.KEEP_STATE:

all: $(LIBS) 

install: all $(ROOTLIBS64) $(ROOTLINKS64)
