#
#ident	"@(#)Makefile	1.2	99/05/20 SMI"
#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.
#
# pkgdefs/SUNWdhcsr/Makefile
#

include ../Makefile.com
DATAFILES += i.initd

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
