#
#pragma ident	"@(#)Makefile	1.4	99/04/26 SMI"
#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libxcurses/sparcv9/Makefile

MAPDIR=	../spec/sparcv9
include ../Makefile.com
include ../../Makefile.lib.64

.KEEP_STATE:

all: $(LIBS)

install: all $(ROOTLIBS64)
