#
#ident	"@(#)Makefile	1.2	96/08/27 SMI"
#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.
#

include ../Makefile.com

DATAFILES += i.preserve i.confupdate

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
