#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	99/11/19 SMI"

include ../Makefile.com

DATAFILES += depend

.KEEP_STATE:

all: $(FILES)

install: all pkg

include ../Makefile.targ
