#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.4	97/11/02 SMI"
#
# lib/gss_mechs/mech_dummy/sparcv9/Makefile

include ../Makefile.com
include ../../../Makefile.lib.64

LIBS=   $(DYNLIB)

.KEEP_STATE:

all: $(LIBS)

install: all $(ROOTLIBS64) $(ROOTLINKS64)

