#
#ident	"@(#)Makefile	1.3	98/12/07 SMI"
#
# Copyright (c) 1998 by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/psradm/Makefile
#

PROG=	psradm

include	../Makefile.cmd

OWNER = root
GROUP = sys

.KEEP_STATE:

all: $(PROG)

install: all $(ROOTUSRSBINPROG)

clean:

lint: lint_PROG

include	../Makefile.targ
