#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.4	99/01/25 SMI"
#
# lib/libbsm/sparcv9/Makefile

MAPDIR=	../spec/sparcv9

include ../Makefile.com
include ../../Makefile.lib.64

.KEEP_STATE:

LIBS = 	$(DYNLIB) $(LINTLIB)

all: $(LIBS)

install: all $(ROOTLIBS64) $(ROOTLINKS64)
