#
# Copyright (c) 1996-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.1	99/05/04 SMI"
#
# cmd/sgs/libelf/sparcv9/Makefile

MAPDIR=		../spec/ia64
include		../Makefile.com

#LINTFLAGS64 +=	-D__sparcv9
MISCOBJS=	$(MISCOBJS64)

.KEEP_STATE:

include		../Makefile.targ.64
