#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	99/06/04 SMI"

include ../Makefile.com

.KEEP_STATE:

DATAFILES += depend

all: $(FILES)
install: all pkg

include ../Makefile.targ
