#
#ident	"@(#)Makefile	1.1	98/06/17 SMI"
#
# Copyright (c) 1998 by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/swap/sparc/Makefile

include ../Makefile.com

install: all $(ROOTUSRSBINPROG32)
