#
#ident	"@(#)Makefile	1.9	99/06/25 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#

include ../Makefile.com

DATAFILES += i.ataconf

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
