#ident	"@(#)Makefile	1.1	99/01/25 SMI"
#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/fn/libxfn/spec/Makefile

include	$(SRC)/lib/Makefile.spec.arch

# no-op targets
install_h private_h check debug tcov analyse:
