#
# Copyright (c) 1999, by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libsecdb/sparc/Makefile
#
#"@(#)Makefile	1.1	99/04/07 SMI"
#

include ../Makefile.com

MAPDIR=	../spec/sparc

.KEEP_STATE:

LIBS +=	$(DYNLIB) $(LINTLIB)
all: $(LIBS)

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
