#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident  "@(#)Makefile   1.1     97/08/25 SMI"
#
# lib/fn/context/onc_ns/libfnsp/i386/Makefile
#

include ../Makefile.com

.KEEP_STATE:

debug install tcov: $(ROOTLIBDIR) $(ROOTLIBS) $(ROOTLINKSCCC)
