#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.3	99/01/25 SMI"
#
# lib/libintl/sparc/Makefile

MAPDIR=	../spec/sparc

include ../Makefile.com

.KEEP_STATE:

all: $(LIBS)

install install_h: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTARLINK) $(ROOTLINT)

lint:	$(LINTLIB)
