#
#pragma ident	"@(#)Makefile	1.4	99/04/26 SMI"
#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libxcurses/sparc/Makefile

MAPDIR=	../spec/sparc
include ../Makefile.com

.KEEP_STATE:

all: $(LIBS) 

install: all $(ROOTLIBS)
