#
#pragma ident	"@(#)Makefile	1.3	98/04/09 SMI"
#
# Copyright (c) 1996-1997 by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/ldap/sparc/Makefile
#
include ../Makefile.com
include ../../Makefile.cmd.64

.KEEP_STATE:

install: $(ALLPROG) $(ROOTPROG64) $(ROOTLINKS64) $(ROOTLINT)

FRC:
