#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.1	99/08/10 SMI"
#
# lib/librcm/sparc/Makefile

MAPDIR=	../spec/sparc
include ../Makefile.com

.KEEP_STATE:

all: $(LIBS) $(STATICLIB)

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
