#
#ident	"@(#)Makefile	1.1	97/06/30 SMI"
#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# psm/stand/lib/boot/sparcv9/sun4u/Makefile
#
# Platform-specific
#

PLATFORM =	sun4u
ARCHVERS =	v9
TOPDIR =	../../../../../..
PLATSRCS =

include ../Makefile.com

include $(TOPDIR)/psm/Makefile.psm.64
