#
#ident	"@(#)Makefile	1.6	96/02/28 SMI"
#
# Copyright (c) 1996 by Sun Microsystems, Inc.
# All rights reserved.

include		$(SRC)/cmd/sgs/tools/Makefile.com

.KEEP_STATE:

all:		native $(PROGS) $(LIBS)

native:		$(NATIVE)

install:	all $(ROOTPROGS) $(ROOTLIBS)

include		$(SRC)/cmd/sgs/tools/Makefile.targ
