#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#
#pragma ident "@(#)Makefile	1.1 97/10/27 SMI"
#
# lib/fn/context/x500/libldap/sparcv9/Makefile
#

include ../Makefile.com
include ../../../../../Makefile.lib.64

.KEEP_STATE:

#BUILD.SO += $(CFLAGS)

debug install tcov: all $(ROOTLIBDIR64) $(ROOTLINKS64)
