#
#ident	"@(#)Makefile	1.2	99/01/25 SMI"
#
# Copyright (c) 1995-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libnsl/i386/Makefile
#

MAPDIR=	../spec/i386

include ../Makefile.com

LIBS += $(DYNLIB) $(LINTLIB)

.KEEP_STATE:

all:	$(LIBS)

install:	all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
