/*
 * @(#)DialogActions.java	1.1	99/05/05 SMI
 *
 * Copyright (c) 1999 by Sun Microsystems, Inc.
 * All rights reserved.
 */
package com.sun.dhcpmgr.client;

/**
 * This interface defines the strings used to differentiate the
 * action events generated by the dialogs.
 */
public interface DialogActions {
    public static final String OK = "ok";
    public static final String CANCEL = "cancel";
    public static final String CREATE = "create";
    public static final String DUPLICATE = "duplicate";
    public static final String EDIT = "edit";
    public static final String DELETE = "delete";
    public static final String DISABLE = "disable";
    public static final String ENABLE = "enable";
}
