#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident  "@(#)Makefile   1.1     97/08/25 SMI"
#
# lib/fn/libfn_p/i386/Makefile
#

include ../Makefile.com

.KEEP_STATE:

debug install tcov: $(ROOTLINKSCCC)
