#
#pragma ident	"@(#)Makefile	1.1	99/05/04 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/gss_mechs/mech_dh/backend/ia64/Makefile
#

include ../Makefile.com
include ../../../../Makefile.lib.64

.KEEP_STATE:

all:    $(LIBS)

install: all  $(ROOTLIBDIR64) .WAIT $(ROOTLIBS64) .WAIT $(ROOTLINKS64)
