#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident "@(#)Makefile	1.2 99/07/27 SMI"
#
#	Makefile for SUNWpamsc package
#

include	../Makefile.com

.KEEP_STATE:

all: $(FILES) depend
install: all pkg

include ../Makefile.targ
