#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident   "@(#)Makefile 1.12     97/12/15 SMI"
#
# usr/src/cmd/cmd-inet/usr.sbin/in.named/tools/nslookup/sparc

include ../../../../../Makefile.cmd

include Makefile.com

include ../../../../../Makefile.targ
.KEEP_STATE:

all: $(PROG) $(HELPFILE)

install: all $(ROOTUSRSBINPROG) $(ROOTLIBHELP) 
