#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.2	99/01/25 SMI"
#
# lib/libtnfprobe/i386/Makefile

MAPDIR=	../spec/i386
include ../Makefile.com

.KEEP_STATE:

install: all $(ROOTLIBS) $(ROOTLINKS)
