#
#ident	"@(#)Makefile	1.5	98/09/30 SMI"
#
# Copyright (c) 1998 by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/sgs/dis/i386/Makefile
#

include		../Makefile.com

.KEEP_STATE:

MACHOBJS=	bits.o tables.o

DEFLIST=	-DAR32WR -DI386 -DRBO -DPORTAR -DELF

include		../Makefile.targ
