#
#pragma ident	"@(#)Makefile	1.3	99/01/25 SMI"
#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libxcurses/sparc/Makefile

MAPDIR=	../spec/sparc
include ../Makefile.com

.KEEP_STATE:

all: $(LIBS) 

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
