#
#ident	"@(#)Makefile	1.1	99/08/19 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
#

include ../Makefile.com

.KEEP_STATE:

DATAFILES += depend

all: $(FILES)
install: all pkg

include ../Makefile.targ
