#
#ident	"@(#)Makefile	1.1	98/02/23 SMI"
#
# Copyright (c) 1998 by Sun Microsystems, Inc.
#

include ../Makefile.com

.KEEP_STATE:

all:		$(LIBRARY)
install:	all $(ROOTLIBS64)

include ../Makefile.targ
include ../../Makefile.sub.64
