#
#ident	"@(#)Makefile	1.1	99/10/20 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
include ../Makefile.com

DATAFILES = i.preserve i.initd depend

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
