#
# Copyright (c) 1996-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.4	99/03/09 SMI"
#
# lib/libdevinfo/i386/Makefile

MAPDIR=	../spec/i386
include ../Makefile.com

all: $(LIBS) $(STATICLIB)

.KEEP_STATE:

install: all $(ROOTLIBS) $(ROOTLINKS) $(ROOTLINT)
