#
#ident	"@(#)Makefile 1.2	96/01/17 SMI"
#
# Copyright (c) 1996, by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libxcurses/src/terminfo/Makefile
#

all:
	@echo these terminfo entries are not currently used by Solaris
	@echo use entries in usr/src/cmd/terminfo
