#
#ident	"@(#)Makefile	1.1	97/08/12 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/nsswitch/dns/sparc/Makefile
#

include ../Makefile.com

.KEEP_STATE:

install: $(ROOTLIBS)
