#
#ident	"@(#)Makefile	1.2	97/05/31 SMI"
#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/setuname/i386/Makefile

.KEEP_STATE:

include ../Makefile.com

install: all $(ROOTPROG32)
