/*
 * Copyright (c) 1999 by Sun Microsystems, Inc.
 * All rights reserved.
 */

#pragma ident	"@(#)confunix.c	1.5	99/10/05 SMI"

/*
 * Boot configuration.
 * In 4.x, this file was generated by config(8)
 * Today, it's merely a place to declare these globals.
 */

#include <sys/bootconf.h>

struct bootobj rootfs, frontfs, backfs, swapfile;
