#! /bin/sh
#
# ident "@(#)preremove 1.7	99/05/27 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#

PATH="/bin:/usr/bin:/usr/sbin:${PATH}"
export PATH

rem_drv -b ${BASEDIR} pcelx
rm -f ${BASEDIR}/dev/pcelx*

exit 0
