#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#
#pragma ident "@(#)Makefile	1.3 97/11/20 SMI"
#
# lib/fn/libfn_p/sparc/Makefile
#

include ../Makefile.com

.KEEP_STATE:

debug install tcov: $(ROOTLIBDIR) $(ROOTLIBS) $(ROOTLINKSCCC)
