#
#ident	"@(#)Makefile.lib	1.57	99/10/10 SMI"
#
# Copyright (c) 1995-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/Makefile.lib
# Definitions common to libraries.
#
# include global definitions; SRC should be defined in the shell.
# SRC is needed until RFE 1026993 is implemented.
#
# Note that the building of profiled libraries is toggled under
# the $(BUILD_PROFS) flag which defaults to $(CH) in Makefile.master.

include		$(SRC)/Makefile.master

LORDER=		lorder
TSORT=		tsort
AWK=		awk
LN=		ln
CAT=		cat

MAPFILE-FLTR=	$(SRC)/lib/common/mapfile-filter

LIBS=		$(LIBRARY) $(LIBRARYCCC)
MACHLIBS=	$(LIBS:%=$(MACH)/%)
MACHLIBS64=	$(LIBS:%=$(MACH64)/%)
PLIB=
PIC_PLIB=
$(BUILD_PROFS)PLIB=	libp/$(LIBRARY)
$(BUILD_PROFS)PIC_PLIB=	libp/$(DYNLIB)
DYNLIB=		$(LIBRARY:.a=.so$(VERS))
DYNLIBPSR=	$(LIBRARY:.a=_psr.so$(VERS))
DYNLIBCCC=	$(LIBRARYCCC:.a=.so$(VERS))
LIBLINKS=	$(LIBRARY:.a=.so)
LIBLINKSCCC=	$(LIBRARYCCC:.a=.so)
LIBNAME=	$(LIBRARY:lib%.a=%)
LIBLINKPATH=
LIBNULL=	null.a
$(BUILD_PROFS)MACHPLIB=	$(MACH)/$(PLIB)
$(BUILD_PROFS)MACHPIC_PLIB=	$(MACH)/$(PIC_PLIB)
$(BUILD_PROFS)MACHPLIB64=	$(MACH64)/$(PLIB)
$(BUILD_PROFS)MACHPIC_PLIB64=	$(MACH64)/$(PIC_PLIB)
ROOTLIBDIR=	$(ROOT)/usr/lib
ROOTLIBDIR64=	$(ROOT)/usr/lib/$(MACH64)
ROOTCCSLIBDIR=	$(ROOT)/usr/ccs/lib
ROOTCCSLIBDIR64=	$(ROOT)/usr/ccs/lib/$(MACH64)
ROOTLIBS=	$(LIBS:%=$(ROOTLIBDIR)/%)
ROOTLIBS64=	$(LIBS:%=$(ROOTLIBDIR64)/%)
ROOTLINKS=	$(ROOTLIBDIR)/$(LIBLINKS)
ROOTLINKS64=	$(ROOTLIBDIR64)/$(LIBLINKS)
ROOTLINKSCCC=	$(ROOTLIBDIR)/$(LIBLINKSCCC)
ROOTLINKSCCC64=	$(ROOTLIBDIR64)/$(LIBLINKSCCC)
ROOTPLIB=
ROOTPIC_PLIB=
ROOTPIC_PLIBLINK=
ROOTPIC_PLIB64=
ROOTPIC_PLIB64LINK=
$(BUILD_PROFS)ROOTPLIB=	$(ROOTLIBDIR)/$(PLIB)
$(BUILD_PROFS)ROOTPIC_PLIB= $(ROOTLIBDIR)/$(PIC_PLIB)
$(BUILD_PROFS)ROOTPIC_PLIBLINK= $(ROOTLIBDIR)/libp/$(LIBLINKS)
$(BUILD_PROFS)ROOTPIC_PLIB64= $(ROOTLIBDIR)/libp/$(MACH64)/$(DYNLIB)
$(BUILD_PROFS)ROOTPIC_PLIB64LINK= $(ROOTLIBDIR)/libp/$(MACH64)/$(LIBLINKS)
ROOTMAN3=     $(ROOT)/usr/share/man/man3
ROOTMAN3FILES=        $(MAN3FILES:%=$(ROOTMAN3)/%)
$(ROOTMAN3FILES) := FILEMODE= 444
$(ROOTMAN3FILES) := OWNER= bin
$(ROOTMAN3FILES) := GROUP= bin

LINTLIB=	llib-l$(LIBNAME).ln
LINTFLAGS=	-uaxs
LINTFLAGS64=	-uaxs
LINTOUT=	lint.out
ARFLAGS=	r
SONAME=		$(DYNLIB)
# For most libraries, we should be able to resolve all symbols at link time,
# either within the library or as dependencies, all text should be pure, and
# combining relocations into one relocation table reduces startup costs.
# All options are tunable to allow overload/omission from lower makefiles.
ZDEFS=          -z defs
ZTEXT=          -z text
ZCOMBRELOC=	-z combreloc
HSONAME=	-h $(SONAME)
PMAP=		-M $(SRC)/lib/common/mapfile_pga_$(MACH)
DYNFLAGS=	$(HSONAME) $(ZTEXT) $(ZDEFS) $(ZCOMBRELOC) $(PMAP)

LDLIBS=		$(LDLIBS.lib)

OBJS=		$(OBJECTS:%=objs/%)
PROFS=		$(OBJECTS:%=profs/%)
PICS=		$(OBJECTS:%=pics/%)
PIC_PROFS=	$(OBJECTS:%=pic_profs/%)

# Declare that all library .o's can all be made in parallel.
# The DUMMY target is for those instances where OBJS, PROFS and PICS
# are empty (to avoid an unconditional .PARALLEL declaration).
.PARALLEL:	$(OBJS) $(PROFS) $(PICS) $(PIC_PROFS) DUMMY

# default value for "portable" source
SRCS=		$(OBJECTS:.o=.c)

# default build of an archive and a shared object,
# overridden locally when extra processing is needed
BUILD.AR=	$(AR) $(ARFLAGS) $@ $(AROBJS)
BUILD.SO=	$(CC) -o $@ -G $(DYNFLAGS) $(PICS) $(LDLIBS)
BUILDCCC.SO=	$(CCC) -o $@ -G $(DYNFLAGS) $(PICS) $(LDLIBS)

# default dynamic library symlink
INS.liblink=		-$(RM) $@; $(LN) $(ROOTLIBDIR)/$(LIBLINKS)$(VERS) $@
$(CH)INS.liblink=	-$(RM) $@; $(SYMLINK) $(LIBLINKPATH)$(LIBLINKS)$(VERS) $@
INS.pliblink=   -$(RM) $@; $(LN) $(ROOTLIBDIR)/libp/$(LIBLINKS)$(VERS) $@
$(CH)INS.pliblink= -$(RM) $@; $(SYMLINK) $(LIBLINKPATH)/libp/$(LIBLINKS)$(VERS) $@
INS.liblinkccc=		-$(RM) $@; $(LN) $(ROOTLIBDIR)/$(LIBLINKSCCC)$(VERS) $@
$(CH)INS.liblinkccc=	-$(RM) $@; $(SYMLINK) $(LIBLINKPATH)$(LIBLINKSCCC)$(VERS) $@

# default 64-bit dynamic library symlink
INS.liblink64=		-$(RM) $@; $(LN) $(ROOTLIBDIR64)/$(LIBLINKS)$(VERS) $@
$(CH)INS.liblink64=	-$(RM) $@; $(SYMLINK) $(LIBLINKPATH)$(LIBLINKS)$(VERS) $@
INS.pliblink64=  -$(RM) $@; $(LN) $(ROOTLIBDIR)/libp/$(MACH64)/$(LIBLINKS)$(VERS) $@
$(CH)INS.pliblink64=    -$(RM) $@; $(SYMLINK) $(LIBLINKPATH)$(LIBLINKS)$(VERS) $@
INS.liblinkccc64=	-$(RM) $@; $(LN) $(ROOTLIBDIR64)/$(LIBLINKSCCC)$(VERS) $@
$(CH)INS.liblinkccc64=	-$(RM) $@; $(SYMLINK) $(LIBLINKPATH)$(LIBLINKSCCC)$(VERS) $@

# Handle different PIC models on different ISAs
# (May be overridden by lower-level Makefiles)

sparc_C_PICFLAGS =	-K pic
i386_C_PICFLAGS =	-K pic
sparcv9_C_PICFLAGS =	-K pic

# should be -K pic but the CC driver is currently broken
sparc_CC_PICFLAGS =	-pic
i386_CC_PICFLAGS = 	-pic
sparcv9_CC_PICFLAGS =	-KPIC

# conditional assignments

$(OBJS)  :=	sparc_CFLAGS += -xregs=no%appl
$(PROFS) :=	sparc_CFLAGS += -xregs=no%appl
$(PROFS) :=	CFLAGS += -p

$(PICS)  :=	sparc_CFLAGS += -xregs=no%appl $(sparc_C_PICFLAGS)
$(PICS)  :=	i386_CFLAGS += $(i386_C_PICFLAGS)
$(PICS)  :=	sparcv9_CFLAGS += -xregs=no%appl $(sparcv9_C_PICFLAGS)
# should be -K pic but the CC driver is currently broken
$(PICS)  :=	CCFLAGS += -pic
$(PICS)  :=	CPPFLAGS += -DPIC -D_TS_ERRNO
$(PICS)  :=	sparcv9_CCFLAGS += -xregs=no%appl $(sparcv9_CC_PICFLAGS)

$(PIC_PROFS) := sparc_CFLAGS += -xregs=no%appl -K pic
$(PIC_PROFS) := i386_CFLAGS += -K pic
$(PIC_PROFS) := sparcv9_CFLAGS += -xregs=no%appl -K PIC
$(PIC_PROFS) := CFLAGS += -p
$(PIC_PROFS) := CPPFLAGS += -DPIC -D_TS_ERRNO
$(PIC_PLIB) := BUILD.SO = $(CC) -o $@ -p -G $(DYNFLAGS) \
				-M ../../mapfile_profile \
				$(PIC_PROFS) $(LDLIBS)

$(LINTLIB):=	LOG = -DLOGGING
$(LIBRARY):=	AROBJS = $(OBJS)
$(BUILD_PROFS)$(PLIB):=	AROBJS = $(PROFS)
$(LIBRARY):=	DIR = objs
$(BUILD_PROFS)$(PLIB):=	DIR = profs
$(DYNLIB):=	DIR = pics
$(DYNLIBCCC):=	DIR = pics

SONAMECCC=	$(DYNLIBCCC)
HSONAMECCC=	-h $(SONAMECCC)
$(DYNLIBCCC):=	DYNFLAGS = $(HSONAMECCC) $(ZTEXT) $(ZDEFS) $(ZCOMBRELOC) \
		-norunpath -nolib

# build rule for "portable" source
objs/%.o profs/%.o pic_profs/%.o pics/%.o: %.c
	$(COMPILE.c) -o $@ $<
	$(POST_PROCESS_O)

objs/%.o profs/%.o pics/%.o: %.cc
	$(COMPILE.cc) -o $@ $<
	$(POST_PROCESS_O)

.PRECIOUS: $(LIBS) $(PLIB)

# Define the majority text domain in this directory.
TEXT_DOMAIN= SUNW_OST_OSLIB

$(ROOTMAN3)/%: %.sunman
	$(INS.rename)

#
# Spec/ABI stuff
#
# Spectranslator Target Architecture
TRANSMACH=	$(MACH)
