#
#pragma ident "@(#)Makefile	1.2	96/09/24 SMI"
#
# Copyright 1996 by Sun Microsystems, Inc.
# All rights reserved.
#

include ../Makefile.com

DATAFILES +=

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
