#
#ident	"@(#)Makefile	1.1	95/03/27 SMI"
#
# Copyright (c) 1995 by Sun Microsystems, Inc.
# All Rights Reserved.
#
# pkgdefs/SUNWkey/Makefile

include ../Makefile.com

DATAFILES += depend

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
