#
# Copyright (c) 1997-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile.targ	1.1	99/01/25 SMI"
#
# lib/libcfgadm/spec/Makefile.targ

LIBRARY	=	libcfgadm.a
VERS	=	.1

OBJECTS	=	cfgadm.o

TRANSCPP =
SPECCPP =
