#
#pragma ident	"@(#)Makefile	1.1	99/08/06 SMI"
#
# Copyright (c) 1991-1999 by Sun Microsystems, Inc.
# All rights reserved
#

include ../Makefile.com

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
