#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident	"@(#)Makefile	1.6	99/07/22 SMI"
#
# lib/storage/libg_fc/sparc/Makefile

include ../Makefile.com

.KEEP_STATE:

all browser debug_browser: $(LIBS)

install debug: all $(ROOTLIBS) $(ROOTLINKS)

include ../Makefile.targ
