# Generated automatically from Makefile.in by configure.
#
# $Id: Makefile.in,v 1.4 1998/06/02 02:41:02 eric Exp $
#
## Makefile for mkisofs.
#
#ident	"@(#)Makefile	1.1	99/10/08 SMI"

#### Start of system configuration section. ####

srcdir = .
LIBS = 

#### End of system configuration section. ####

PROG=dump isodump isovfy isoinfo

include ../../Makefile.cmd

CFLAGS += -I.
LDFLAGS=

all: dump isodump isovfy isoinfo

install: all

clean:

include ../../Makefile.targ
