#
#ident	"@(#)Makefile	1.1	97/06/06 SMI"
#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/sysdef/sparc/Makefile

include ../Makefile.com

install: all $(ROOTUSRSBINPROG32)
