#
#ident	"@(#)Makefile	1.2	95/06/13 SMI"
#
# Copyright (c) 1995 by Sun Microsystems, Inc.
#
# cmd/adb/sparc/kadb/sun4u/Makefile
#
# The common makefile does all the work. 
#

# this deliberately avoids macro names ARCH and KERNARCH for local control
KARCH= sun4u

ARCHVERS=v9

KARCHOBJS=fpasciisr.o

MMU=	sfmmu

include ../Makefile.com
