#ident	"@(#)Makefile.targ	1.1	99/01/25 SMI"
#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libtnfctl/spec/Makefile.targ

LIBRARY	=	libtnfctl.a
VERS	=	.1

OBJECTS	=	tnfctl.o

SPECCPP =
