#
#ident	"@(#)Makefile	1.1	97/08/12 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/nsswitch/nisplus/i386/Makefile
#

include ../Makefile.com

.KEEP_STATE:

install: all $(ROOTLIBS)

