#ident	"@(#)Makefile.targ	1.1	99/01/25 SMI"
#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libadm/spec/Makefile.targ

LIBRARY	=	libw.a
VERS	=	.1

OBJECTS	=	widechar.o

TRANSCPP =	-F

SPECCPP =	-I..
