#
#ident	"@(#)Makefile	1.1	98/06/17 SMI"
#
# Copyright (c) 1998 by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/swap/sparcv9/Makefile

include ../Makefile.com
include ../../Makefile.cmd.64

install: all $(ROOTUSRSBINPROG64)
