#
#ident	"@(#)Makefile	1.4	95/03/24 SMI"
#
# Copyright (c) 1995 by Sun Microsystems, Inc.
# All rights reserved.
#

include ../Makefile.com

DATAFILES += i.preserve

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
