#
#ident  "@(#)Makefile 1.1     97/11/19 SMI"
#
# Copyright (c) 1995 - 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/gss_mechs/mech_dh/dh1024/sparc/Makefile
#

include ../Makefile.com

.KEEP_STATE:

all:    $(LIBS)

install:    all $(ROOTLIBDIR) .WAIT $(ROOTLIBS) .WAIT $(ROOTLINKS)
