#
#ident	"@(#)Makefile	1.1	97/06/30 SMI"
#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# psm/stand/lib/boot/sparc/sun4m/Makefile
#
# Platform-specific, but shared between platforms.
# Bogusly SPARC Version 7 dependent.
#

PLATFORM =	sun4m
ARCHVERS =	v7
TOPDIR =	../../../../../..
PLATSRCS =

include ../Makefile.com
