#
#ident	"@(#)Makefile	1.12	98/12/04 SMI"
#
# Copyright (c) 1989,1998 by Sun Microsystems, Inc.
# All rights reserved.

PROG= tr

include ../Makefile.cmd

.KEEP_STATE:

CFLAGS += -v

all: $(PROG)

install: all $(ROOTPROG)

clean:

lint:	lint_PROG

include ../Makefile.targ
