#
#ident	"@(#)Makefile	1.1	97/10/01 SMI"
#
# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
# cmd/ls/sparcv9/Makefile

include ../Makefile.com
include ../../Makefile.cmd.64

# doesn't install ROOTXPG4PROG64 yet, no such place
install: all $(ROOTPROG64)
