#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile.targ	1.1	99/08/15 SMI"
#
# lib/libpctx/spec/Makefile.targ

LIBRARY	=	libpctx.a
VERS	=	.1

OBJECTS	=	pctx.o
