# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident "@(#)Makefile	1.2 97/10/21 SMI"
#
# lib/fn/libxfn.1/sparcv9/Makefile
#

include ../Makefile.com
include ../../../Makefile.lib.64

.KEEP_STATE:

BUILDCCC.SO += $(CCFLAGS)

debug install tcov: $(ROOTLIBDIR64) $(ROOTLIBS64)

