DEV_NM
NT_PATH
SET PATH=C:\MKSNT;C:\MASM611\BIN;C:\MASM611\BINR;%PATH%
SET LIB=C:\MASM611\LIB;C:\MSVC\LIB
SET INCLUDE=C:\MASM611\INCLUDE
SET INIT=C:\MASM611\INIT
SET HELPFILES=C:\MASM611\HELP\*.HLP
SET ASMEX=C:\MASM611\SAMPLES
SET TMP=C:\TMP
SET TEMP=C:\TMP
SET TZ=PST8PDT
REM SET PATH TO USE MICROSOFT VISUAL C++, AHEAD OF MASM
SET PATH=C:\MSVC\BIN;%PATH%
REM SET OTHER VISUAL C++ VARIABLES
SET TOOLROOTDIR=C:\MSVC
SET INCLUDE=C:\MSVC\INCLUDE;C:\MSVC\MFC\INCLUDE;%INCLUDE%
SET LIB=C:\MSVC\LIB;C:\MSVC\MFC\LIB;%LIB%
SET INIT=C:\MSVC;%INIT% 
REM nmake -k TARGET
nmake -k TARGET
if not errorlevel 2 goto SUCESS
goto FAILED
:SUCESS
echo > .done
goto END
:FAILED
goto END
:END
