#
#ident	"@(#)Makefile	1.4	96/10/15 SMI"
#
# Copyright (c) 1994, by Sun Microsystems, Inc.
# All rights reserved.
#
# psm/stand/lib/sparc/sun4u/Makefile
#
# Platform-specific, but shared between platforms.
#

PLATFORM =	sun4u
ARCHVERS =	v9
TOPDIR =	../../../../../..
PLATSRCS =	modpath.c

include ../Makefile.com
