#ident	"@(#)Makefile.targ	1.1	99/01/25 SMI"
#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libtnf/spec/Makefile.targ

LIBRARY	=	libtnf.a
VERS	=	.1

OBJECTS	=	tnf_process_disable.o	\
		tnf.o

SPECCPP =	-I.. -I../..
