#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#pragma ident "@(#)Makefile 1.1	99/03/19 SMI" 
#
# lib/cfgadm_plugins/scsi/sparc/Makefile
#

MAPDIR=	../spec/sparc
include ../Makefile.com

.KEEP_STATE:

install: all $(ROOTLIBS) $(ROOTLINKS) 
