#! /bin/sh
#
# ident  "@(#)preremove 1.3     99/10/07 SMI"
#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
 
PATH="/usr/bin:/usr/sbin:${PATH}"
export PATH

EXIT=0

rem_drv -b ${BASEDIR} hid || EXIT=1

rem_drv -b ${BASEDIR} hubd || EXIT=1

rem_drv -b ${BASEDIR} usb_mid || EXIT=1

rem_drv -b ${BASEDIR} scsa2usb || EXIT=1

case ${ARCH} in
	i386)
		rem_drv -b ${BASEDIR} uhci || EXIT=1
	;;
	sparc)
		rem_drv -b ${BASEDIR} ohci || EXIT=1
	;;
esac

exit $EXIT
