#
#ident	"@(#)Makefile	1.1	98/02/24 SMI"
#
# Copyright (c) 1998 by Sun Microsystems, Inc.
#

include ../Makefile.com

.KEEP_STATE:

all:		$(LIBRARY)
install:	all $(ROOTLIBS)

include ../Makefile.targ
