#
#ident	"@(#)Makefile	1.2	99/05/14 SMI"
#
# Copyright (c) 1993 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/nsswitch/xfn/i386/Makefile
#

include ../Makefile.com

.KEEP_STATE:

install: all $(ROOTLIBS)

