#ident	"@(#)Makefile.targ	1.1	99/01/25 SMI"
#
# Copyright (c) 1998-1999 by Sun Microsystems, Inc.
# All rights reserved.
#
# lib/libsec/spec/Makefile.targ

LIBRARY	=	libsec.a
VERS	=	.1

OBJECTS	=	acl.o

