#
#ident	"@(#)Makefile	1.1	98/07/17 SMI"
#
# Copyright (c) 1998 by Sun Microsystems, Inc.
# All rights reserved.
#

PROG= clinfo

include ../Makefile.cmd

CFLAGS += -v

.KEEP_STATE:

all: $(PROG) 

install: all $(ROOTUSRSBINPROG)

clean:

lint:	lint_PROG

include ../Makefile.targ
