#
# Copyright (c) 1999 by Sun Microsystems, Inc.
# All rights reserved.
#
#ident	"@(#)Makefile	1.1	99/09/23 SMI"

MODULE = ipc.so
MDBTGT = kvm

MODSRCS = ipc.c

include ../../../../Makefile.cmd
include ../../Makefile.ia32
include ../../../Makefile.module
