#
#ident	"@(#)Makefile	1.1	96/06/07 SMI"
#
# Copyright (c) 1993 - 1996, by Sun Microsystems, Inc.
# All rights reserved.
#

include ../Makefile.com

DATAFILES += depend

.KEEP_STATE:

all: $(FILES)
install: all pkg

include ../Makefile.targ
