# Copyright (c) 1997, by Sun Microsystems, Inc.
# All rights reserved.
#
#ident  "@(#)Makefile   1.1     97/09/04 SMI"
#
# lib/fn/context/fs/host/sparcv9/Makefile
#

include ../Makefile.com
include ../../../../../Makefile.lib.64

.KEEP_STATE:

BUILDCCC.SO += $(CCFLAGS)

debug install tcov: $(ROOTLIBDIR64) $(ROOTLIBS64) 
