#
#ident	"@(#)Makefile	1.3	96/10/15 SMI"
#
# Copyright (c) 1994, by Sun Microsystems, Inc.
# All rights reserved.
#
# psm/stand/lib/sparc/sun4d/Makefile
#
# Platform-specific, but shared between platforms.
# Bogusly SPARC Version 7 dependent.
#

PLATFORM =	sun4d
ARCHVERS =	v7
TOPDIR =	../../../../../..
PLATSRCS =	modpath.c

include ../Makefile.com
