#
#ident	"@(#)Makefile	1.7	98/11/10 SMI"
#
# Copyright (c) 1994-1998 by Sun Microsystems, Inc.
# All rights reserved.
#

include		../Makefile.com

.KEEP_STATE:

ASFLAGS +=	-D__sparcv9 $(sparcv9_XARCH)

install:	all $(ROOTLIB64)/$(PROG)

include		../Makefile.targ
